.github/workflows/CI.yml, .gitignore, build.gradle, src/test/java/com/amazon/opendistroforelasticsearch/ad/cluster/diskcleanup/IndexCleanupTests.java, src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ADBatchAnomalyResultTransportActionTests.java, src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyDetectorJobTransportActionTests.java, src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/CronTransportActionTests.java
Signed-off-by: dblock <dblock@amazon.com>
Fixes CI by building all the dependencies.
Only runs tests, no integ tests, packaging or distribution. 
WDYT? Would need to fix all the stuff I removed from CI and the 4 failing tests afterwards, but does give us a green build.
- https://github.com/opensearch-project/job-scheduler/pull/5
- https://github.com/opensearch-project/common-utils/pull/4
=> Build using local dependencies, re-enable CI

.github/workflows/CI.yml, build.gradle, release-notes/opensearch-anomaly-detection.release-notes-1.0.0.0-beta1.md
Bumps the plugin to version `1.0.0.0-beta1` and its related dependencies (`common-utils`, `job-scheduler`). Also updates CI workflow to updated `1.0.0.0-beta1` versions.
=> Bump plugin + dependencies to version 1.0.0.0-beta1

.github/workflows/CI.yml, build.gradle
Change to `main` branch for OpenSearch to pass build.
Check this [build](https://github.com/opensearch-project/anomaly-detection/pull/47/checks?check_run_id=2615441771), it will throw such exception when build with beta1
```
positiveTimeSetting(String,Setting<TimeValue>,Property,Property)
.positiveTimeSetting(
^
method Setting.positiveTimeSetting(String,TimeValue,Property...) is not applicable
(argument mismatch; Setting<TimeValue> cannot be converted to TimeValue)
method Setting.positiveTimeSetting(String,Setting<TimeValue>,TimeValue,Property...) is not applicable
(argument mismatch; Property cannot be converted to TimeValue)
``` …
=> use main branch of OpenSearch in CI

src/main/java/org/opensearch/ad/caching/CacheBuffer.java, src/test/java/org/opensearch/ad/caching/CacheBufferTests.java
We cannot invoke "com.amazon.opendistroforelasticsearch.ad.ml.ModelState.getModel()" when "valueRemoved" is null. This PR fixes the bug to guard the getModel call with a null check.
Testing done:
1. added a unit test to reproduce the bug.  
- [ Y ] Commits are signed per the DCO using --signoff 
=> Fix nullpointerexception bug

.github/workflows/CI.yml
Now that OpenSearch core has been frozen for `1.0`, build and test against this version.
=> Update CI to run against core 1.0 branch

src/main/java/org/opensearch/ad/AnomalyDetectorRunner.java, src/main/java/org/opensearch/ad/transport/IndexAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/ad/transport/PreviewAnomalyDetectorTransportAction.java, src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java
If user has no permission to read index, we should block creating/updating detector with that index.
https://github.com/opensearch-project/anomaly-detection/issues/36
=> check if user has permission to read index when create/update/preview detector

README.md
Documentation was pointed to ODFE link (https://opendistro.github.io/for-elasticsearch-docs/docs/ad/) rather than OpenSearch link (https://docs-beta.opensearch.org/docs/ad/). Updated. 
Resolved old link. 
=> Update README.md Documentation link

src/main/java/org/opensearch/ad/ml/EntityColdStarter.java, src/test/java/org/opensearch/ad/TestHelpers.java, src/test/java/org/opensearch/ad/ml/EntityColdStarterTests.java
While collecting training data, we continue searching even if no data range has data.  This bug can cause "No [ranges] specified for the [date_range] aggregation" exception printed out.  This PR fixed that by returning empty training data instead of logging exceptions.
Testing done:
1. testing on a cluster with sparse data.  Verified we don't log exceptions anymore.
- [ Y ] Commits are signed per the DCO using --signoff 
=> Fix empty range for cold start bug

.github/workflows/link-check-workflow.yml, README.md
Adds a broken link checker workflow. Runs on pushes & pull requests to `main`. Based off of the `opensearch-plugins` [PR](https://github.com/opensearch-project/opensearch-plugins/pull/54).
=> Add broken link check workflow

.github/workflows/CI.yml, build.gradle
Bumps plugin version to `1.0.0.0`. Note that `rc1` versions of the dependencies are still being used here, since `integTest` is failing due to an issue related to OpenSearch's distribution downloader. Changes will need to be made to bump the versions to `1.0.0` once the upstream fix has been made. I've opened #109 to track this, which also includes a link to the upstream issue.
=> Bump plugin version to 1.0.0.0

.github/workflows/CI.yml, build.gradle
Bumps the versions by removing the `rc1` qualifier of OpenSearch, common-utils, and job-scheduler dependencies.
Resolves #109 
=> Bump plugin dependencies to 1.0.0.0

.github/workflows/CI.yml, build.gradle
Backporting #114 to `1.x` branch.
=> [BACKPORT] [1.x] Bump plugin dependencies to 1.0.0.0

build.gradle, src/main/java/org/opensearch/ad/AnomalyDetectorPlugin.java, src/main/java/org/opensearch/ad/AnomalyDetectorRunner.java, src/main/java/org/opensearch/ad/constant/CommonErrorMessages.java, src/main/java/org/opensearch/ad/model/ADTask.java, src/main/java/org/opensearch/ad/model/ADTaskAction.java, src/main/java/org/opensearch/ad/model/ADTaskType.java, src/main/java/org/opensearch/ad/settings/AnomalyDetectorSettings.java, src/main/java/org/opensearch/ad/task/ADBatchTaskCache.java, src/main/java/org/opensearch/ad/task/ADBatchTaskRunner.java, src/main/java/org/opensearch/ad/task/ADHCBatchTaskCache.java, src/main/java/org/opensearch/ad/task/ADTaskCacheManager.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/ad/transport/ADBatchTaskRemoteExecutionTransportAction.java, src/main/java/org/opensearch/ad/transport/ForwardADTaskRequest.java, src/main/java/org/opensearch/ad/transport/ForwardADTaskTransportAction.java, src/test/java/org/opensearch/ad/HistoricalAnalysisIntegTestCase.java, src/test/java/org/opensearch/ad/TestHelpers.java, src/test/java/org/opensearch/ad/task/ADTaskCacheManagerTests.java, src/test/java/org/opensearch/ad/transport/ADBatchAnomalyResultTransportActionTests.java, src/test/java/org/opensearch/ad/transport/SearchADTasksTransportActionTests.java
Support historical analysis for HC detector. For single entity detector, we just need to create one AD task as it has only one ML model. For HC detector, AD will run separate ML model for each entity. So we will create individual task for each entity. And we will have one detector level task to track overall state like progress. Will save detector level task id as parent task id in entity task.
The main steps for HC detector historical analysis:
1. Get top entities
2. Calculate how many entities can run concurrently based on settings and cluster resources. Then start N task lanes to run entities. Each lane will run 1 entity. For every entity task will get all data node's state and dispatch entity task to the node with least node.
3. If one …
=> support historical analysis for HC detector

src/main/java/org/opensearch/ad/AnomalyDetectorProfileRunner.java, src/main/java/org/opensearch/ad/constant/CommonErrorMessages.java, src/main/java/org/opensearch/ad/constant/CommonName.java, src/main/java/org/opensearch/ad/model/ADTaskAction.java, src/main/java/org/opensearch/ad/model/ADTaskProfile.java, src/main/java/org/opensearch/ad/model/ADTaskState.java, src/main/java/org/opensearch/ad/model/ADTaskType.java, src/main/java/org/opensearch/ad/model/DetectorProfile.java, src/main/java/org/opensearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java, src/main/java/org/opensearch/ad/rest/handler/IndexAnomalyDetectorJobActionHandler.java, src/main/java/org/opensearch/ad/task/ADBatchTaskRunner.java, src/main/java/org/opensearch/ad/task/ADHCBatchTaskCache.java, src/main/java/org/opensearch/ad/task/ADTaskCacheManager.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/ad/transport/ADTaskProfileNodeResponse.java, src/main/java/org/opensearch/ad/transport/ADTaskProfileTransportAction.java, src/main/java/org/opensearch/ad/transport/DeleteAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/ad/transport/ForwardADTaskRequest.java, src/main/java/org/opensearch/ad/transport/ForwardADTaskTransportAction.java, src/main/java/org/opensearch/ad/transport/GetAnomalyDetectorResponse.java, src/main/java/org/opensearch/ad/transport/GetAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/ad/util/RestHandlerUtils.java
Signed-off-by: Yaliang Wu <ylwu@dev-dsk-ylwu-2c-e500d1cf.us-west-2.amazon.com>
1. Profile API: return task profiles of HC historical analysis
2. Get detector API: return both realtime and historical tasks if user add task=true
3. Error handling: If task keeps running for a long time, get task profile to check if historical analysis still running. If not running, reset task state as stopped. This can handle coordinating node crash.
4. Error handling: clean stale running entities in coordinating node cache in case worker nodes crash or fail to send back entity task done message. This can handle worker node crash.
5. Change rate limiter to thread.schedule to avoid blocking thread.
This PR is only for reviewing the main logic. UT and IT will be in separate PR. …
=> support HC task profiles in profile API;error handling

README.md, build.gradle, src/main/java/org/opensearch/ad/transport/AnomalyDetectorJobTransportAction.java, src/main/java/org/opensearch/ad/transport/DeleteAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/ad/transport/GetAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/ad/transport/IndexAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/ad/transport/PreviewAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/ad/util/ParseUtils.java, src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/mock/transport/MockAnomalyDetectorJobTransportActionWithUser.java, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java, src/test/java/org/opensearch/ad/transport/DeleteAnomalyDetectorTransportActionTests.java, src/test/java/org/opensearch/ad/transport/IndexAnomalyDetectorTransportActionTests.java, src/test/java/org/opensearch/ad/transport/PreviewAnomalyDetectorTransportActionTests.java
In current implementation, when user update detector,  we will replace detector user as current user. In some cases, it may cause detector creator lose access of detector. Check more details in #124 
Based on discussion with @skkosuri-amzn and PM, we plan to fix this issue quickly by blocking replacing detector user when update. User can't update detector user after creation.
https://github.com/opensearch-project/anomaly-detection/issues/124
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#deve …
=> don't replace detector user when update

src/main/java/org/opensearch/ad/AnomalyDetectorPlugin.java, src/main/java/org/opensearch/ad/rest/RestDeleteAnomalyResultsAction.java, src/main/java/org/opensearch/ad/transport/DeleteAnomalyResultsAction.java, src/main/java/org/opensearch/ad/transport/DeleteAnomalyResultsTransportAction.java
With historical analysis, user can generate much more anomaly result in a short time, especially for HC detector. AD plugin will roll over anomaly result index if its doc count reaches some limit, and will delete roll-over index after some period (30 days by default). So if user run historical analysis, it may generate too many AD results and speed up the rollover and AD result index cleanup. 
This PR adds delete anomaly result API. User can use this API to delete anomaly results with specific query like delete all anomaly results of one detector/task.
Sample request
```
DELETE _plugins/_anomaly_detection/detectors/results
{
"query": {
"bool": {
"filter": [
{
"term": {
"detector_id": {
"value": "6tZminoBaXxjTubPk0k6"
}
}
}
]
}
}
}
```
By submitting …
=> add delete anomaly results API

src/main/java/org/opensearch/ad/AnomalyDetectorPlugin.java, src/main/java/org/opensearch/ad/cluster/HourlyCron.java, src/main/java/org/opensearch/ad/model/ADTask.java, src/main/java/org/opensearch/ad/settings/AnomalyDetectorSettings.java, src/main/java/org/opensearch/ad/task/ADBatchTaskRunner.java, src/main/java/org/opensearch/ad/task/ADTaskCacheManager.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/ad/transport/CronNodeRequest.java, src/main/java/org/opensearch/ad/transport/CronRequest.java, src/main/java/org/opensearch/ad/transport/CronTransportAction.java
Maintain running historical tasks in hour cron. 
1. Clean child tasks and AD result of deleted detector level tasks.
2. Check if running historical analysis tasks still running. If not running, reset task as stopped; otherwise, check if there are any stale running entities and clean up.
=> maintain running historical task in hourly cron

src/main/java/org/opensearch/ad/AnomalyDetectorProfileRunner.java, src/main/java/org/opensearch/ad/EntityProfileRunner.java, src/main/java/org/opensearch/ad/caching/PriorityCache.java, src/main/java/org/opensearch/ad/constant/CommonErrorMessages.java, src/main/java/org/opensearch/ad/feature/SearchFeatureDao.java, src/main/java/org/opensearch/ad/ml/CheckpointDao.java, src/main/java/org/opensearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java, src/main/java/org/opensearch/ad/rest/handler/IndexAnomalyDetectorJobActionHandler.java, src/main/java/org/opensearch/ad/settings/AnomalyDetectorSettings.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/ad/transport/AnomalyDetectorJobTransportAction.java, src/main/java/org/opensearch/ad/transport/DeleteAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/ad/transport/DeleteAnomalyResultsTransportAction.java, src/main/java/org/opensearch/ad/transport/GetAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/ad/transport/IndexAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/ad/transport/PreviewAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/ad/transport/SearchAnomalyDetectorInfoTransportAction.java, src/main/java/org/opensearch/ad/transport/StatsAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/ad/transport/StopDetectorTransportAction.java, src/main/java/org/opensearch/ad/transport/handler/ADSearchHandler.java, src/main/java/org/opensearch/ad/util/ParseUtils.java, src/main/java/org/opensearch/ad/util/RestHandlerUtils.java, src/test/java/org/opensearch/ad/caching/PriorityCacheTests.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/transport/AnomalyDetectorJobTransportActionTests.java, src/test/java/org/opensearch/ad/transport/GetAnomalyDetectorTests.java, src/test/java/org/opensearch/ad/transport/PreviewAnomalyDetectorTransportActionTests.java, src/test/java/org/opensearch/ad/util/ParseUtilsTests.java
1. Avoid sending back verbose error message and wrong 500 error to user. This is for security consideration.
2. Fix hard code query size of historical analysis
=> avoid sending back verbose error message and wrong 500 error to user; fix hard code query size of historical analysis

src/main/java/org/opensearch/ad/MemoryTracker.java, src/main/java/org/opensearch/ad/settings/AnomalyDetectorSettings.java, src/main/java/org/opensearch/ad/util/MathUtil.java, src/test/java/org/opensearch/ad/MemoryTrackerTests.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/settings/AnomalyDetectorSettingsTests.java
We split and distribute models to different nodes to avoid large models on a single node. The splitting is unnecessary after introducing compact rcf as the model is smaller (at least 4x smaller). Splitting also undoes the shared point store optimization among trees. Also, splitting brings complications when computing expected values. Thus, this PR disables splitting by increasing the desired model size. We won't split a model whose size is less than the desired size.
This PR adjusts max features and shingle size accordingly to avoid huge models without explicit benefits.
This PR also adjusts the model size formula due to the change https://github.com/aws/random-cut-forest-by-aws/pull/265. I will update the rcf version once rcf 2.0 is released in maven.
Experiments on estimated vs actual …
=> Disable model splitting in single-stream detectors

build.gradle
Signed-off-by: lai <laijiang@amazon.com>
This pr enables junit 5 test framework with advanced testing features while maintaining backwards compatibility with current test cases in junit 4.
=> enable junit 5

build.gradle, src/main/java/org/opensearch/ad/AnomalyDetectorProfileRunner.java, src/main/java/org/opensearch/ad/NodeState.java, src/main/java/org/opensearch/ad/NodeStateManager.java, src/main/java/org/opensearch/ad/common/exception/NotSerializedADExceptionName.java, src/main/java/org/opensearch/ad/ml/EntityModel.java, src/main/java/org/opensearch/ad/transport/AnomalyResultTransportAction.java, src/main/java/org/opensearch/ad/transport/EntityResultTransportAction.java, src/main/java/org/opensearch/ad/util/ExceptionUtil.java, src/test/java/org/opensearch/ad/common/exception/NotSerializedADExceptionNameTests.java, src/test/java/org/opensearch/ad/ml/EntityModelTests.java, src/test/java/org/opensearch/ad/transport/AnomalyDetectorJobTransportActionTests.java, src/test/java/org/opensearch/ad/transport/MultiEntityResultTests.java
OpenSearch restricts the kind of exceptions that can be thrown over the wire (Read OpenSearchException.OpenSearchExceptionHandle). Since we cannot add our exception like ResourceNotFoundException without modifying OpenSearch's code, we must unwrap the NotSerializableExceptionWrapper and check its root cause message. This PR adds checks all AD exceptions in such cases. Previously, we only checked a couple of them.
Previously, we wrap all exceptions thrown in AD using one of AnomalyDetectionExceptions. The wrap brings a complication to NotSerializableExceptionWrapper thrown over the wire as NotSerializableExceptionWrapper won't keep the original AnomalyDetectionExceptions object and only keeps the cause message. Therefore, we won't be able to restore the original exception encapsulated …
=> Handle more AD exceptions thrown over the wire/network

.github/workflows/CI.yml, build.gradle, src/main/java/org/opensearch/ad/util/Bwc.java, src/test/java/org/opensearch/ad/transport/CronTransportActionTests.java
Signed-off-by: Vacha <vachshah@amazon.com>
Bumping up`anomaly-detection` to build with OpenSearch main which is 1.1.0 and use 1.1.0.0 for `job-scheduler` and `common-utils`.
As with the branching and release strategy for the project opensearch-project/.github#13
Here is how it should look like:
Plugin/library main builds out of OpenSearch main.
Plugin/library 1.x builds out of OpenSearch 1.x.
Plugin/library 1.0 builds out of OpenSearch 1.0.
This allows us to fail fast and get ready for release.
As part of adding backwards compatibility test framework, we are developing tests as an example in Anomaly Detection which needs the bwc framework from OpenSearch main.
Ref: opensearch-project/OpenSearch#1002
Meta issue: opensearch-project/opensearch-build#90 
#156  …
=> Bumping anomaly-detection to 1.1.0.0 to use OpenSearch (main) 1.1.0

.github/workflows/CI.yml, build.gradle
Requires https://github.com/opensearch-project/common-utils/pull/58 and https://github.com/opensearch-project/job-scheduler/pull/49, and cleaned up on top of https://github.com/opensearch-project/anomaly-detection/pull/175.
Signed-off-by: dblock <dblock@amazon.com>
Fix assembly with `-Dbuild.snapshot=true`. The full syntax required passing the version of job scheduler and common utils, which would cause us to need a custom script for the bundle build. Changed build.gradle to default those to the same build as OpenSearch (e.g. 1.0.0 becomes 1.0.0.0 and 1.0.0-SNAPSHOT becomes 1.0.0.0-SNAPSHOT).
So to build a snapshot:
```
./gradlew assemble --no-daemon --refresh-dependencies -DskipTests=true -Dopensearch.version=1.0.0-SNAPSHOT -Dbuild.snapshot=true
```
Closes #173.
By submitting this pull …
=> Fix snapshot assemble and build 1.1.0.

.github/workflows/CI.yml, DEVELOPER_GUIDE.md
Adding bwc tests introduced in #158 to run with CI for `anomaly-detection`. Also adding the test run commands in the developer guide.
[opensearch-build#222](https://github.com/opensearch-project/opensearch-build/issues/222)
=> Add bwc tests to run with CI

build.gradle, src/main/java/org/opensearch/ad/caching/PriorityCache.java, src/main/java/org/opensearch/ad/indices/AnomalyDetectionIndices.java, src/main/java/org/opensearch/ad/ml/EntityColdStarter.java, src/main/java/org/opensearch/ad/ml/ModelManager.java, src/main/java/org/opensearch/ad/settings/AnomalyDetectorSettings.java, src/main/java/org/opensearch/ad/transport/EntityResultTransportAction.java, src/main/java/org/opensearch/ad/transport/handler/MultiEntityResultHandler.java, src/main/java/org/opensearch/ad/util/BulkUtil.java, src/main/java/org/opensearch/ad/util/MathUtil.java, src/main/java/org/opensearch/ad/util/ThrowingSupplierWrapper.java, src/test/java/org/opensearch/AnomalyResultResponse1_0.java, src/test/java/org/opensearch/BwcTests.java, src/test/java/org/opensearch/CronNodeRequest1_0.java, src/test/java/org/opensearch/CronRequest1_0.java, src/test/java/org/opensearch/ad/AbstractADTest.java, src/test/java/org/opensearch/ad/EntityProfileRunnerTests.java, src/test/java/org/opensearch/ad/NodeStateManagerTests.java, src/test/java/org/opensearch/ad/indices/UpdateMappingTests.java, src/test/java/org/opensearch/ad/ml/ModelManagerTests.java, src/test/java/org/opensearch/ad/transport/ADResultBulkResponseTests.java, src/test/java/org/opensearch/ad/transport/MultiEntityResultTests.java, src/test/java/org/opensearch/ad/transport/handler/AbstractIndexHandlerTest.java, src/test/java/org/opensearch/ad/transport/handler/AnomalyResultHandlerTests.java, src/test/java/org/opensearch/ad/transport/handler/MultiEntityResultHandlerTests.java, src/test/java/org/opensearch/ad/util/BulkUtilTests.java, src/test/java/org/opensearch/ad/util/ThrowingSupplierWrapperTests.java
First, this PR adds an empty string check in PriorityCache.
Second, in EntityColdStarter, this PR clears samples after using them for training.
Third, this PR removes unused fields and local variables in ModelManager and BulkUtil.
Fourth, this PR decreases the concurrent preview from 5 to 2, with a conservative purpose to reduce potential GC.
Fifth, this PR finishes unit tests owed due to my previous PRs. 99% code of the PR is about tests.
Testing done:
1. Added unit tests.
2. made sure the basic e2e workflow still works. …
=> Bug fixes and unit tests

build.gradle, src/main/java/org/opensearch/ad/AnomalyDetectorPlugin.java, src/main/java/org/opensearch/ad/AnomalyDetectorProfileRunner.java, src/main/java/org/opensearch/ad/constant/CommonName.java, src/main/java/org/opensearch/ad/model/DetectorProfile.java, src/main/java/org/opensearch/ad/settings/AnomalyDetectorSettings.java, src/main/java/org/opensearch/ad/stats/StatNames.java, src/main/java/org/opensearch/ad/stats/suppliers/ModelsOnNodeCountSupplier.java, src/main/java/org/opensearch/ad/stats/suppliers/ModelsOnNodeSupplier.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/ad/transport/ProfileNodeResponse.java, src/main/java/org/opensearch/ad/transport/ProfileResponse.java, src/main/java/org/opensearch/ad/transport/ProfileTransportAction.java, src/test/java/org/opensearch/BwcTests.java, src/test/java/org/opensearch/ad/AnomalyDetectorProfileRunnerTests.java, src/test/java/org/opensearch/ad/MultiEntityProfileRunnerTests.java, src/test/java/org/opensearch/ad/stats/ADStatsTests.java, src/test/java/org/opensearch/ad/stats/suppliers/ModelsOnNodeSupplierTests.java, src/test/java/org/opensearch/ad/transport/ADStatsNodesTransportActionTests.java, src/test/java/org/opensearch/ad/transport/ProfileTests.java, src/test/java/org/opensearch/ad/transport/ProfileTransportActionTests.java, src/test/java/org/opensearch/search/aggregations/metrics/CardinalityProfileTests.java
Previously, the number of models we show on the stats/profile API is unbounded. The unbounded models can cause potential memory/network issues if a vast number of models exist. This PR sets an upper bound and makes the bound a dynamic setting. Due to the above change, the models may not be complete, and thus I added a model_count to the stats/profile API to show the actual models present.
This PR also fixed bugs:
First, AnomalyDetectorProfileRunner used a listener instead of delegateListener, which can cause the profile API to return early before collecting all outputs.
Second, I forgot to support the multi-category fields in AnomalyDetectorProfileRunner.profileEntityStats. This PR adds support there. In detail, profile API needs to report total entities. We can use cardinality …
=> Limit the max models shown on the stats and profile API

src/main/java/org/opensearch/ad/constant/CommonErrorMessages.java, src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/main/java/org/opensearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/ad/util/ParseUtils.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/util/ParseUtilsTests.java
If detector category field changed, frontend may not be able to render AD result for different detector types correctly. For example, if detector changed from HC to single entity detector, AD result page may show multiple anomaly result points on the same time point if there are multiple entities have anomaly results. If single-category HC changed category field from IP to error type, the AD result page may show both IP and error type in top entities list. That's confusing. So we decide to block updating detector category field. …
=> block updating detector category field

src/main/java/org/opensearch/ad/cluster/HashRing.java, src/main/java/org/opensearch/ad/model/ADTask.java, src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/main/java/org/opensearch/ad/rest/RestDeleteAnomalyResultsAction.java, src/main/java/org/opensearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java, src/main/java/org/opensearch/ad/rest/handler/IndexAnomalyDetectorJobActionHandler.java, src/main/java/org/opensearch/ad/settings/AnomalyDetectorSettings.java, src/main/java/org/opensearch/ad/task/ADBatchTaskRunner.java, src/main/java/org/opensearch/ad/task/ADHCBatchTaskCache.java, src/main/java/org/opensearch/ad/task/ADTaskCacheManager.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/ad/transport/AnomalyDetectorJobTransportAction.java, src/main/java/org/opensearch/ad/transport/DeleteAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/ad/transport/ForwardADTaskTransportAction.java, src/test/java/org/opensearch/ad/TestHelpers.java, src/test/java/org/opensearch/ad/mock/transport/MockAnomalyDetectorJobTransportActionWithUser.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/rest/HistoricalAnalysisRestApiIT.java, src/test/java/org/opensearch/ad/task/ADTaskCacheManagerTests.java, src/test/java/org/opensearch/ad/task/ADTaskManagerTests.java, src/test/java/org/opensearch/ad/transport/AnomalyDetectorJobTransportActionTests.java
Reset realtime task state when get latest detector task. If job is disabled, we should set realtime task state as stopped.
=> reset realtime task state

.github/workflows/CI.yml, release-notes/opensearch-anomaly-detection.release-notes-1.1.0.0.md
Bumps the OpenSearch core branch from `1.x` to `1.0` in the CI workflow.
=> [1.1] Bump OpenSearch core to 1.1 in CI

.github/workflows/CI.yml, build.gradle, docs/ml-rfc.md, src/main/java/org/opensearch/ad/AnomalyDetectorJobRunner.java, src/main/java/org/opensearch/ad/AnomalyDetectorPlugin.java, src/main/java/org/opensearch/ad/feature/CompositeRetriever.java, src/main/java/org/opensearch/ad/indices/AnomalyDetectionIndices.java, src/main/java/org/opensearch/ad/ratelimit/CheckpointReadWorker.java, src/main/java/org/opensearch/ad/settings/AnomalyDetectorSettings.java, src/main/java/org/opensearch/ad/transport/AnomalyResultTransportAction.java, src/main/java/org/opensearch/ad/transport/IndexAnomalyDetectorTransportAction.java, src/test/java/org/opensearch/ad/indices/AnomalyDetectionIndicesTests.java, src/test/java/org/opensearch/ad/indices/InitAnomalyDetectionIndicesTests.java, src/test/java/org/opensearch/ad/indices/RolloverTests.java, src/test/java/org/opensearch/ad/indices/UpdateMappingTests.java, src/test/java/org/opensearch/ad/transport/MultiEntityResultTests.java
This PR (hopefully, as I cannot reproduce the failure locally) fixed flaky tests in MultiEntityResultTests. The tests are flaky, maybe because we expect two pages in our pagination, but we may create more than two pages due to a race condition. Please read comments in MultiEntityResultTests for detail.
This PR also changes the log level of the updating real-time task log from info to debug. We don't need info as Opensearch prints the log repeatedly in each interval. Also, I changed the log message in ADTaskManager to match what the relevant code does.
This PR also enables auto-expand replication for AD job indexes. The job scheduler puts both primary and replica shards in the hash ring. Enabling auto-expand the number of replicas based on the number of data nodes (up to 20) in the cluster …
=> Fix flaky test and log level/msgs and enable auto-expand replication

src/main/java/org/opensearch/ad/settings/AnomalyDetectorSettings.java, src/main/java/org/opensearch/ad/settings/LegacyOpenDistroAnomalyDetectorSettings.java
Current batch task setting and HC max running entities settings are too conservative as we set these quite small numbers before performance testing. 
After performance testing, we tune these settings to a general number which can speed up historical analysis and will not cause too much load.
=> tune AD batch task and HC running entity setting based on performance test result

src/test/java/org/opensearch/ad/settings/AnomalyDetectorSettingsTests.java, src/test/java/org/opensearch/ad/task/ADTaskManagerTests.java
Fix failed UT caused by dynamic setting update in PR #230 
=> fix failed UT caused by dynamic setting update

src/test/java/org/opensearch/ad/settings/AnomalyDetectorSettingsTests.java, src/test/java/org/opensearch/ad/task/ADTaskManagerTests.java
=> [Backport to 1.x]fix failed UT caused by dynamic setting update (#234)

src/test/java/org/opensearch/ad/settings/AnomalyDetectorSettingsTests.java, src/test/java/org/opensearch/ad/task/ADTaskManagerTests.java
=> [Backport to 1.1]fix failed UT caused by dynamic setting update (#234)

build.gradle
[Backport 1.1] Add javadoc utf8 encoding support in AD
#244
=> [Backport 1.1] Add javadoc utf8 encoding support in AD

build.gradle
Add javadoc utf8 encoding support in AD0
#244
=> Add javadoc utf8 encoding support in AD

build.gradle
[Backport 1.x] Add javadoc utf8 encoding support in AD
#244
=> [Backport 1.x] Add javadoc utf8 encoding support in AD

build.gradle, src/main/java/org/opensearch/ad/AnomalyDetectorPlugin.java, src/main/java/org/opensearch/ad/cluster/ADClusterEventListener.java, src/main/java/org/opensearch/ad/cluster/ADNodeInfo.java, src/main/java/org/opensearch/ad/cluster/HashRing.java, src/main/java/org/opensearch/ad/model/ADTaskProfile.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/ad/util/DiscoveryNodeFilterer.java, src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/cluster/ADClusterEventListenerTests.java, src/test/java/org/opensearch/ad/cluster/HashRingTests.java, src/test/java/org/opensearch/ad/e2e/DetectionResultEvalutationIT.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/transport/AnomalyDetectorJobTransportActionTests.java
We only record AD version of data nodes in HashRing. But the test cluster created by infra team has remote_cluster_clients node which server external REST request. For task profile, the request will go to the remote_cluster_clients node first, then send broadcast to gather task profile on all data nodes. Data nodes will send back task profile based on the remote AD version ( remote_cluster_clients node), as we don’t record  remote_cluster_clients node’s AD version, data node will think it’s incompatible node then send null task profile back check https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/transport/ADTaskProfileNodeResponse.java#L69, …
=> fix null AD version of non-data-type node

build.gradle, src/main/java/org/opensearch/ad/AnomalyDetectorPlugin.java, src/main/java/org/opensearch/ad/cluster/ADClusterEventListener.java, src/main/java/org/opensearch/ad/cluster/ADNodeInfo.java, src/main/java/org/opensearch/ad/cluster/HashRing.java, src/main/java/org/opensearch/ad/model/ADTaskProfile.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/ad/util/DiscoveryNodeFilterer.java, src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/cluster/ADClusterEventListenerTests.java, src/test/java/org/opensearch/ad/cluster/HashRingTests.java, src/test/java/org/opensearch/ad/e2e/DetectionResultEvalutationIT.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/transport/AnomalyDetectorJobTransportActionTests.java
* fix null AD version of non-data-type node
* fix flaky test
Backport PR #253 to 1.1
=> [Backport to 1.1] fix null AD version of non-data-type node (#253)

build.gradle, src/main/java/org/opensearch/ad/AnomalyDetectorPlugin.java, src/main/java/org/opensearch/ad/cluster/ADClusterEventListener.java, src/main/java/org/opensearch/ad/cluster/ADNodeInfo.java, src/main/java/org/opensearch/ad/cluster/HashRing.java, src/main/java/org/opensearch/ad/model/ADTaskProfile.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/ad/util/DiscoveryNodeFilterer.java, src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/cluster/ADClusterEventListenerTests.java, src/test/java/org/opensearch/ad/cluster/HashRingTests.java, src/test/java/org/opensearch/ad/e2e/DetectionResultEvalutationIT.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/transport/AnomalyDetectorJobTransportActionTests.java
* fix null AD version of non-data-type node
* fix flaky test
Backport PR #253 to 1.x
=> [Backport to 1.x] fix null AD version of non-data-type node (#253)

src/main/java/org/opensearch/ad/ml/CheckpointDao.java, src/main/java/org/opensearch/ad/ratelimit/CheckpointWriteWorker.java, src/test/java/org/opensearch/ad/ml/CheckpointDaoTests.java
The following failure happens because the sample size is randomly generated.  If the size is 0, the assertion about a non-empty sample checkpoint would be false. This PR (hopefully) fixed the test by using a non-zero sample size.
CI: https://tinyurl.com/6fbf7nae
org.opensearch.ad.ml.CheckpointDaoTests > testMapperFailure FAILED
java.lang.AssertionError
at __randomizedtesting.SeedInfo.seed([3870AE3C6CD8C213:61F4DC7F9D698B03]:0)
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at org.opensearch.ad.ml.CheckpointDaoTests.testMapperFailure(CheckpointDaoTests.java:772)
Testing done:
1. gradle build
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> Fix flaky test  CheckpointDaoTests.testMapperFailure

src/main/java/org/opensearch/ad/caching/DoorKeeper.java, src/main/java/org/opensearch/ad/caching/PriorityCache.java, src/test/java/org/opensearch/ad/caching/PriorityCacheTests.java
In many workloads, and especially in heavy tailed workloads, unpopular items account for a considerable portion of all accesses. This phenomenon implies that if we model each entity appearing, the majority of the models are assigned to items that are not likely to appear
more than once. Hence, to further reduce the size of model memory usage and reduce the number of unnecessary cold starts, we have used the Doorkeeper mechanism that enables us to avoid allocating models to most tail objects.
Door keepers reset their states every hour in the maintenance window.  It is fine to do so when a detector's interval is less than an hour.  But when a detector's interval is more than one hour, door keepers will keep forgetting that it has seen the detector' entities and refrained from admitting …
=> Fixed a bug when door keepers unnecessarily reset their states

src/main/java/org/opensearch/ad/transport/SearchTopAnomalyResultTransportAction.java
Adds support for searching over detectors that have a specified custom result index (see #276). When retrieving detector info, checks for any set custom result index, and adds it to the list of indices to search over. 
Confirmed it works for custom & non-custom-result-index detectors, confirmed pagination works
closes #280 
=> Support custom result indices in multi-category filtering API

src/test/java/org/opensearch/ad/indices/CustomIndexTests.java
* Latest commit was merged before rebasing with main which led to merging issues. On latest commit the name of method `AnomalyDetectionIndices.isValidResultIndex` changed to `AnomalyDetectionIndices.isValidResultIndexMapping` inorder to more accuretly reflect what function was doing. However since it wasn't rebased with main before merging new unit tests were added with the old name and they were never changed.
* This PR changes these unit test naming 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CO …
=> fixed unit test by changing name of method to most up to date

src/main/java/org/opensearch/ad/transport/SearchTopAnomalyResultTransportAction.java
Signed-off-by: Tyler Ohlsen ohltyler@amazon.com
Fixes a bug where the range query can fail when parsing `java.time.Instant`s in OpenSearch's `RangeQueryBuilder`, when constructing the internal query used to fetch anomaly results.
Error seen: `can not write type [class java.time.Instant]`
The class can't be parsed properly. To fix, we convert the Instant to a `long` using `toEpochMilli()`.
Similar issue: https://github.com/opendistro-for-elasticsearch/index-management/pull/373
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-cer …
=> Fix Instant parsing bug in multi category filtering API

.github/workflows/dco.yml
Signed-off-by: Amit Galitzky amgalitz@amazon.com
Adding working flow to check whether commits are signed as per DCO.
[#256](https://github.com/opensearch-project/anomaly-detection/issues/256)
=> Add DCO Check Workflow

src/main/java/org/opensearch/ad/rest/RestSearchAnomalyResultAction.java, src/main/java/org/opensearch/ad/transport/SearchAnomalyResultTransportAction.java, src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/model/AnomalyDetectorTests.java, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java, src/test/java/org/opensearch/ad/transport/SearchAnomalyResultActionTests.java
In current implementation, we always query AD results from default index. Actually detector result page doesn't need to query default index if detector is using custom result index. And for API users, they may need to query AD results from custom result index only as well.
This PR supports searching AD result from custom result index only if user specify "?only_query_custom_result_index=true" when call search result API.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CO …
=> support only searching results in custom result index

release-notes/opensearch-anomaly-detection.release-notes-1.2.0.0.md
Signed-off-by: Jackie Han <hnyng@amazon.com>
Add 1.2.0.0 release notes
https://github.com/opensearch-project/anomaly-detection/issues/229
=> Add 1.2.0.0 release notes

src/main/java/org/opensearch/ad/task/ADHCBatchTaskCache.java, src/main/java/org/opensearch/ad/task/ADTaskCacheManager.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/ad/transport/AnomalyResultResponse.java, src/main/java/org/opensearch/ad/transport/AnomalyResultTransportAction.java, src/test/java/org/opensearch/ad/task/ADTaskCacheManagerTests.java, src/test/java/org/opensearch/ad/task/ADTaskManagerTests.java
https://github.com/opensearch-project/anomaly-detection/issues/290
> When starting a historical HC job for the first time, it seems to finish but reports the state as STOPPED instead of FINISHED.
This is a known issue for HC detector. When multiple entities send back task done message to coordinator node, coordinator node will update detector level task state&progress, if one entity is updating detector level task, all other entity task will be ignored. For example, HC detector has 3 entities, all of them finished almost the same time, so first entity can update detector level task as RUNNING, second and third entities task done messages will be ignored. So detector level task will remain RUNNING state. Then get detector API will reset task …
=> wait for some time to get semaphore when set HC detector task as done

src/main/java/org/opensearch/ad/task/ADHCBatchTaskCache.java, src/main/java/org/opensearch/ad/task/ADTaskCacheManager.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/ad/transport/AnomalyResultResponse.java, src/main/java/org/opensearch/ad/transport/AnomalyResultTransportAction.java, src/test/java/org/opensearch/ad/task/ADTaskCacheManagerTests.java, src/test/java/org/opensearch/ad/task/ADTaskManagerTests.java
… (#300)
* wait for some time to get semaphore when set HC detector task as done
* fix HC detector stay on initializing forever bug
=> [Backport to 1.2] wait for some time to get semaphore when set HC detector task as done (#300)

src/main/java/org/opensearch/ad/task/ADHCBatchTaskCache.java, src/main/java/org/opensearch/ad/task/ADTaskCacheManager.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/ad/transport/AnomalyResultResponse.java, src/main/java/org/opensearch/ad/transport/AnomalyResultTransportAction.java, src/test/java/org/opensearch/ad/task/ADTaskCacheManagerTests.java, src/test/java/org/opensearch/ad/task/ADTaskManagerTests.java
… (#300)
* wait for some time to get semaphore when set HC detector task as done
* fix HC detector stay on initializing forever bug
=> [Backport to 1.x] wait for some time to get semaphore when set HC detector task as done (#300)

src/main/java/org/opensearch/ad/transport/ValidateAnomalyDetectorTransportAction.java
Added General Settings switch case in `ValidateAnomalyDetectorTransportAction`. This case not existing led to a bug where message for max number of HC or single entity detectors weren't shown. 
Error message on frontend now displays correct message instead of blank. 
=> added switch case for general settings issues

release-notes/opensearch-anomaly-detection.release-notes-1.2.0.0.md
Updating release notes for 1.2.0.0 backend, mainly bug fixes added
=> updated release notes for 1.2 backend

release-notes/opensearch-anomaly-detection.release-notes-1.2.0.0.md
Changed release notes to use asterisks instead of dashes
=> changed release notes dashes to asterisks

src/main/java/org/opensearch/ad/transport/SearchAnomalyResultTransportAction.java, src/test/java/org/opensearch/ad/transport/SearchAnomalyResultActionTests.java
Detector list page will search both default and custom result indices. For a new cluster, if no default/custom result created yet, the detector list page will not show any detector as the backend will throw "No indices found" exception.
This PR removed that exception, just search all default result indices and will return empty SearchResponse to frontend. 
=> don't throw exception if no result indices found when search both default and custom result index

build.gradle
Signed-off-by: Sarat Vemulapalli <vemulapallisarat@gmail.com>
Removing securemock dependency for AD as its not used for unit tests anymore.
=> Dropping securemock dependency

build.gradle
Signed-off-by: Sarat Vemulapalli <vemulapallisarat@gmail.com>
Backporting #331 to 1.x
=> [Backport 1.x] Dropping securemock depedency

src/main/java/org/opensearch/ad/constant/CommonErrorMessages.java, src/main/java/org/opensearch/ad/model/ADEntityTaskProfile.java, src/main/java/org/opensearch/ad/model/DetectorProfileName.java, src/main/java/org/opensearch/ad/model/IntervalTimeConfiguration.java, src/main/java/org/opensearch/ad/rest/handler/AbstractAnomalyDetectorActionHandler.java, src/main/java/org/opensearch/ad/util/RestHandlerUtils.java, src/test/java/org/opensearch/action/admin/indices/mapping/get/IndexAnomalyDetectorActionHandlerTests.java, src/test/java/org/opensearch/action/admin/indices/mapping/get/ValidateAnomalyDetectorActionHandlerTests.java, src/test/java/org/opensearch/ad/ADIntegTestCase.java, src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/TestHelpers.java, src/test/java/org/opensearch/ad/model/ADEntityTaskProfileTests.java, src/test/java/org/opensearch/ad/model/AnomalyDetectorTests.java, src/test/java/org/opensearch/ad/model/DetectorInternalStateTests.java, src/test/java/org/opensearch/ad/model/DetectorProfileTests.java, src/test/java/org/opensearch/ad/model/EntityProfileTests.java, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java, src/test/java/org/opensearch/ad/transport/ADTaskProfileTests.java, src/test/java/org/opensearch/ad/transport/GetAnomalyDetectorTransportActionTests.java, src/test/java/org/opensearch/ad/transport/ValidateAnomalyDetectorResponseTests.java, src/test/java/org/opensearch/ad/transport/ValidateAnomalyDetectorTransportActionTests.java, src/test/java/org/opensearch/ad/util/ParseUtilsTests.java
Added more unit testing for validation API as well as for some model classes that either didn't have any tests or were missing a unit test. 
Split PR into two separate ones. This first one has all the additional validation testing, including some additional model testing. Second PR will have more integration tests, more tests in ad.model package and other files. 
=> Adding more unit tests for validation API and some model classes

.gitignore
Signed-off-by: dblock <dblock@dblock.org>
When updating to 1.2.4 a .zip file was not git add-ed, had to do it manually.
=> Do not git ignore job scheduler dir, used.

.github/ISSUE_TEMPLATE/bug_report.md
Removes outdated `Beta` label
Closes #342
=> Remove Beta label from bug issue template

src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java
Added new integration for security enabled tests. Checks validation API with different user permissions. 
Separate PR since I had issues with CI workflow at first for these tests. Should be solved now. 
=> Added validation integration tests with security

build.gradle
=> upgrade gson to 2.8.9

.github/workflows/link-check-workflow.yml, build.gradle
Backporting PR that added the commons-lang3. This was added in order to fix a missing dependency issue that appeared in 1.3.0. This same issue is now appearing in 1.2.4 opensearch build process. 
https://github.com/opensearch-project/anomaly-detection/issues/359
=> [Backport to 1.2] fix missing dependency:commons-lang3 (#350)

build.gradle
Removed jcenter dependency as it is no longer operating. We have mavenCentral() as a fallback.
resolves #357 
=> remove jcenter dependency

build.gradle
Backporting jcenter dependency removal to 1.2 branch
=> [Backport to 1.2] removed jcenter dependency (#361)

build.gradle
backport jcenter dependency removal to 1.x
=> [Backport 1.x] removed jcenter dependency (#361)

.github/workflows/backport.yml, DEVELOPER_GUIDE.md
Adds backport workflow to allow automatic backport PR creation as we merge to main or label PR. Explanation of script added to documentation.
* We can label previously closed PRs and the action will run.
* As of right now we have to manually delete the branch that the bot creates. This could be changed in the future to be automatic.
resolves #330 
=> ADD auto backport functionality to AD

src/test/java/org/opensearch/ad/ODFERestTestCase.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java
Fixes 3 tests that were using the default client to perform manual changes to system indices, such as checking if they exist, creating them, deleting them. Note that this is necessary sometimes to put the cluster in a certain state for testing out certain scenarios. To properly perform these actions, we can use the existing admin client.
Advantages of admin client:
- overrides any strict deprecation failures related to direct access to system indices
- overrides any permissions failures related to security-enabled cluster
More context behind these changes:
We were seeing occasional failures when trying to execute these tests against certain cluster configurations, including bundled binary clusters with security enabled. By changing to use …
=> Use admin client for system index updates in integ tests

src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/e2e/DetectionResultEvalutationIT.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/rest/HistoricalAnalysisRestApiIT.java
Fixes several flaky tests that can be solved by adding some sleep time between creating detector and the next action. 
Additionally `org.opensearch.ad.e2e.DetectionResultEvalutationIT.testDataset` has been failing due to precision occasionally being around 0.4-0.5 so minPrecision was lowered to 0.4. 
Currently draft PR as I am continuing to investigate other flaky tests that aren't simply solved by adding more sleep time or are difficult to replicate.
#278  
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/m …
=> Fixing Flaky Integration Tests

build.gradle
Removing remaining reference to jcenter. This was initially removed from `buildscript` section of `build.gradle` in this PR: #361 but was never removed from repositories list outside of the `buildscript` section.
#357 
=> remove remaining jcenter reference

.github/workflows/backport.yml, DEVELOPER_GUIDE.md
Backporting [this commit](https://github.com/opensearch-project/anomaly-detection/commit/387412f83639b6a8d03036df144c02ed820bddd5) to `1.x` branch.
Had to manually backport since the backport bot doesn't handle merge-commit PRs, which was the case for this PR ([link](https://github.com/opensearch-project/anomaly-detection/pull/368))
Also, I've blocked that type of PR merge in the repo settings so that this can't happen again …
=> [Backport 1.x] adding auto backport workflow plus documentation

build.gradle, src/main/java/org/opensearch/ad/common/exception/ADValidationException.java, src/main/java/org/opensearch/ad/constant/CommonErrorMessages.java, src/main/java/org/opensearch/ad/constant/CommonName.java, src/main/java/org/opensearch/ad/feature/SearchFeatureDao.java, src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/main/java/org/opensearch/ad/model/DetectorValidationIssue.java, src/main/java/org/opensearch/ad/model/DetectorValidationIssueType.java, src/main/java/org/opensearch/ad/model/IntervalTimeConfiguration.java, src/main/java/org/opensearch/ad/model/ValidationAspect.java, src/main/java/org/opensearch/ad/rest/AbstractAnomalyDetectorAction.java, src/main/java/org/opensearch/ad/rest/handler/AbstractAnomalyDetectorActionHandler.java, src/main/java/org/opensearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java, src/main/java/org/opensearch/ad/rest/handler/ModelValidationActionHandler.java, src/main/java/org/opensearch/ad/rest/handler/ValidateAnomalyDetectorActionHandler.java, src/main/java/org/opensearch/ad/settings/AnomalyDetectorSettings.java, src/main/java/org/opensearch/ad/transport/ValidateAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/ad/util/ParseUtils.java, src/test/java/org/opensearch/action/admin/indices/mapping/get/IndexAnomalyDetectorActionHandlerTests.java, src/test/java/org/opensearch/action/admin/indices/mapping/get/ValidateAnomalyDetectorActionHandlerTests.java, src/test/java/org/opensearch/ad/ADIntegTestCase.java, src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/TestHelpers.java, src/test/java/org/opensearch/ad/e2e/DetectionResultEvalutationIT.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/transport/ValidateAnomalyDetectorTransportActionTests.java
This PR adds two new changes.
1.  Adds model (“non-blocker”) type validation to the current validation API. The model type validation is non-blocking in nature meaning that any warning that arise are simply suggestions or added information to the user about which configuration could be changed in order to increase the likelihood of model training completing successfully. These validation checks could also potentially recommend a specific detector interval or window delay value that the user can try to use.
* Every-time model type validation is called, it initially also calls the blocker validation since there its not possible to run non-blocker checks if there is a blocking issue initially. 
2. Adds a check that the given timefield exists in the index mapping and also that it is of type …
=> Adding Model Type Validation to Validate API ("non-blocker")

src/test/java/org/opensearch/ad/e2e/DetectionResultEvalutationIT.java
Fixed test so it checks window delay recommendation takes into account rounding up that occurs in validation logic.
=> Fixing failing IT for validate API

src/main/java/org/opensearch/ad/feature/AbstractRetriever.java, src/test/java/org/opensearch/ad/feature/NoPowermockSearchFeatureDaoTests.java
Previously, when writing a feature using filter aggregation, we failed with EndRunException: Failed to parse aggregation.. due to missing logic parsing the result. This PR adds the parsing logic.
Testing done:
1. added unit tests
2. end-to-end testing.
Detector with filter aggregation:
```
{
"name": "Second-Test-Detector-4",
"description": "ok rate",
"time_field": "snapshotAt",
"indices": [
"lse20-*"
],
"feature_attributes": [
{
"feature_id": "deny_max",
"feature_name": "deny max",
"feature_enabled": true,
"importance": 1,
"aggregation_query": {
"t_shirts": {
"filter": {
"bool": {
"should": [
{
"term": {
"issueType": "foo"
}
},
{
"term": {
"issueType": "bar"
}
}
],
"minimum_should_match": "1",
"boost": 1
}
},
"aggs": {
"impactUniqueAccounts": {
"cardinality": {
"field": "account"
}
}
}
} …
```
=> Support writing features using filter aggregation

.github/workflows/CI.yml, src/main/java/org/opensearch/ad/constant/CommonErrorMessages.java, src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java
Now that staging docker images are continuously updated in dockerhub every time there's a new bundle build, we can use the upcoming version to pull in the images, construct the dockerfile, and run the integ tests with security enabled in them.
This updates the tag to match the naming strategy used in dockerhub.
Also updates:
- error message in validation API typo
- 2 broken tests as pointed out in #430. The issue is that a validation check causes failures due to the source index not having a valid time field, so this adds a sample doc with a valid time field before detector creation.
TODO:
#430 
For more information on …
=> Fix docker tag to unblock running integ tests in CI

build.gradle
Signed-off-by: dblock <dblock@dblock.org>
Backport of https://github.com/opensearch-project/anomaly-detection/pull/439 to 1.x.
Half of https://github.com/opensearch-project/anomaly-detection/issues/433.
=> [Backport 1.x] Upgraded to protostuff 1.8.0.

build.gradle
Signed-off-by: dblock <dblock@dblock.org>
Backport of https://github.com/opensearch-project/anomaly-detection/pull/439 to 1.3.
Half of https://github.com/opensearch-project/anomaly-detection/issues/433.
=> [Backport 1.3] Upgraded to protostuff 1.8.0.

src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/test/java/org/opensearch/ad/model/AnomalyDetectorTests.java
Changed the default description field to be set to an empty string instead of a null field. This means that description should also be changed from a `required` field as listed in [documentation](https://opensearch.org/docs/latest/monitoring-plugins/ad/api/#create-anomaly-detector) to an `optional` field since if detector description is missing then it will be filled as an empty string. 
Currently if there is a missing description field, the backend still creates the detector even though it is listed as `required` which causes issues on the frontend which tries to parse a null a value unsuccessfully when getting the relevant detector. 
Other option is to throw an exception if description is missing and hence enforce the `required` …
=> Changed default description to empty string instead of null

.gitignore, src/main/java/org/opensearch/ad/model/ADTaskProfile.java, src/test/java/org/opensearch/ad/transport/ADTaskProfileTests.java
1. Fixed bug in `ADTaskProfile.toXContent()` which added `ENTITY_TASK_PROFILE_FIELD` instead of `LATEST_HC_TASK_RUN_TIME_FIELD` when `latestHCTaskRunTime` was present in constructor. Also added a test case for this. This previously would cause a parsing exception if a non null `latestHCTaskRunTime` was given to constructor.
2. Added `._.DS_Store` to `.gitignore` as its a file that gets auto created by macOS Finder which isn't relevant.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#dev …
=> Fixed ADTaskProfile toXContent bug and added to .gitignore

build.gradle, src/main/java/org/opensearch/ad/model/EntityProfileName.java, src/main/java/org/opensearch/ad/rest/handler/ModelValidationActionHandler.java, src/test/java/org/opensearch/ad/AnomalyDetectorPluginTests.java, src/test/java/org/opensearch/ad/AnomalyDetectorProfileRunnerTests.java, src/test/java/org/opensearch/ad/TestHelpers.java, src/test/java/org/opensearch/ad/common/exception/ADValidationExceptionTests.java, src/test/java/org/opensearch/ad/model/ADEntityTaskProfileTests.java, src/test/java/org/opensearch/ad/model/AnomalyResultBucketTests.java, src/test/java/org/opensearch/ad/model/DetectorInternalStateTests.java, src/test/java/org/opensearch/ad/model/DetectorProfileTests.java, src/test/java/org/opensearch/ad/model/EntityProfileTests.java, src/test/java/org/opensearch/ad/model/MergeableListTests.java, src/test/java/org/opensearch/ad/transport/ADTaskProfileTests.java, src/test/java/org/opensearch/ad/transport/EntityProfileTests.java, src/test/java/org/opensearch/ad/transport/ValidateAnomalyDetectorResponseTests.java, src/test/java/org/opensearch/ad/transport/ValidateAnomalyDetectorTransportActionTests.java, src/test/java/org/opensearch/ad/util/ParseUtilsTests.java
This PR adds some tests to various classes that had low coverage as well as removes any unnecessary files from the `jacocoExclusion` list on `build.gradle`. We had some files there that were either already above the coverage minimum or didn’t exist anymore. Specifically `.../model.*` was listed and with additional testing added here and in previous PR (https://github.com/opensearch-project/anomaly-detection/pull/335) 34 classes were taken off the exclusion list and now only 2 classes from model package are still excluded.
I wont close the related issue (https://github.com/opensearch-project/anomaly-detection/issues/424) yet since more work needs to be done addressing the TODOs, potentially reducing coverage minimums and finishing rest of …
=> Reduced jacoco exclusions and added more tests

build.gradle
Removes unnecessary `-oss` flavor from `build.gradle`. OpenSearch exported `oss` flavor flag until now (all versions up to 1.3.0) and will remove it after. https://github.com/opensearch-project/OpenSearch/pull/1751
resolves #2 
=> Remove oss flavor

src/test/java/org/opensearch/ad/model/AnomalyResultBucketTests.java
Changed `<>` to `<String, Object>` since `Cannot use '<>' with anonymous inner classes` error occurs for JDK 8. This compiled fine on main since that now only uses jdk11 and up but 1.x branch can't compile without this code change as it supports java 8.
=> Fixing jdk 8 compile issue for 1.x only

build.gradle
Signed-off-by: Amit Singh <snghes@amazon.com>
-Dbuild.version_qualifier
Part of https://github.com/opensearch-project/opensearch-build/issues/1632.
=> Add support for -Dbuild.version_qualifier

build.gradle
Revert alpha1 default version as it requires more changes than expected. Refer to `ml-commons` PR https://github.com/opensearch-project/ml-commons/pull/257
This PR revert the default version change to make sure CI can work.
=> revert alpha1 default version

build.gradle, src/forbidden/ad-test-signatures.txt, src/test/java/org/opensearch/action/admin/indices/mapping/get/IndexAnomalyDetectorActionHandlerTests.java, src/test/java/org/opensearch/action/admin/indices/mapping/get/ValidateAnomalyDetectorActionHandlerTests.java, src/test/java/org/opensearch/ad/AnomalyDetectorJobRunnerTests.java, src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/HistoricalAnalysisRestTestCase.java, src/test/java/org/opensearch/ad/NodeStateManagerTests.java, src/test/java/org/opensearch/ad/cluster/DailyCronTests.java, src/test/java/org/opensearch/ad/cluster/HashRingTests.java, src/test/java/org/opensearch/ad/cluster/HourlyCronTests.java, src/test/java/org/opensearch/ad/cluster/MasterEventListenerTests.java, src/test/java/org/opensearch/ad/e2e/DetectionResultEvalutationIT.java, src/test/java/org/opensearch/ad/ml/CheckpointDaoTests.java, src/test/java/org/opensearch/ad/ml/CheckpointDeleteTests.java, src/test/java/org/opensearch/ad/ml/EntityColdStarterTests.java, src/test/java/org/opensearch/ad/mock/plugin/MockReindexPlugin.java, src/test/java/org/opensearch/ad/plugin/MockReindexPlugin.java, src/test/java/org/opensearch/ad/rest/ADRestTestUtils.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/rest/HistoricalAnalysisRestApiIT.java, src/test/java/org/opensearch/ad/transport/ADResultBulkTransportActionTests.java, src/test/java/org/opensearch/ad/transport/AnomalyResultTests.java, src/test/java/org/opensearch/ad/transport/DeleteTests.java, src/test/java/org/opensearch/ad/transport/IndexAnomalyDetectorTransportActionTests.java, src/test/java/org/opensearch/ad/transport/PreviewAnomalyDetectorTransportActionTests.java, src/test/java/org/opensearch/ad/transport/handler/AbstractIndexHandlerTest.java, src/test/java/org/opensearch/ad/transport/handler/AnomalyResultHandlerTests.java
1. Added a new custom signature file for `forbiddenAPIsTest`
2. Replaced `printStackTrace` calls with more specific `logger.error()`
3. Added `Locale.ROOT` too a lot of string.format() calls.
4. Added `Charset.defaultCharset()` to calls to read files in testing
5. Removed `ignoreFailures = true` for forbiddenAPIsTest, **this is pretty much the most long lasting change as build will now fail if we add new code that with `format` not using `Locale` instead of stacking up a list of hundreds of warning over time (this can be changed back so only warnings are shown and not failures if it proves to be too constrictive.)**
resolves #422
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> Changed forbiddenAPIsTest files and made relevant forbidden fixes

build.gradle, src/test/java/org/opensearch/ad/e2e/DetectionResultEvalutationIT.java, src/test/java/org/opensearch/ad/transport/ValidateAnomalyDetectorTransportActionTests.java
Testing out new gradle plugin that retries failed test.
* Added this to both unit tests and integ tests
* `maxFailures`: "The maximum number of test failures that are allowed before retrying is disabled." (set to 10)
* `maxRetries`: "The maximum number of times to retry an individual test." (set to 10)
* `getFailOnPassedAfterRetry`: "Whether tests that initially fail and then pass on retry should fail the task." (set to **false** since if it passes once its good enough to pass build)
**Will be re-running workflows a few times on this PR to try this out and potentially adjust max failures/retries setting.** https://blog.gradle.org/gradle-flaky-test-retry-plugin
#451 
By submitting this pull request, I confirm that my contribution is made …
=> Adding test-retry plugin

.github/workflows/CI.yml, build.gradle, src/main/java/org/opensearch/ad/indices/AnomalyDetectionIndices.java, src/main/java/org/opensearch/ad/rest/handler/AbstractAnomalyDetectorActionHandler.java, src/test/java/org/opensearch/ad/TestHelpers.java, src/test/java/org/opensearch/ad/indices/RolloverTests.java
Changes in this PR:
1. Updates default version qualifier to alpha1
2. Fixes more mapping type changes and return type of method based of core changes
3. updates Jackson databind to 2.13.2.2, jackson core to 2.13.2 and jacson annotations to 2.13.2.
`Jackson databind 2.13.2.2` fixes this issue https://github.com/opensearch-project/anomaly-detection/issues/436
4. Removes JDK 14 support
resolves https://github.com/opensearch-project/anomaly-detection/issues/436
resolves #479 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certifi …
=> Changes default version to 2.0.0-alpha1 and fixes CVE-2020-36518

src/main/java/org/opensearch/ad/feature/CompositeRetriever.java, src/main/java/org/opensearch/ad/transport/AnomalyResultTransportAction.java, src/test/java/org/opensearch/ad/feature/NoPowermockSearchFeatureDaoTests.java, src/test/java/org/opensearch/ad/transport/MultiEntityResultTests.java
Previously, CompositeRetriever throws an IllegalArgumentException in the presence of empty results, which gets translated to internal failure and increments AD failure count. When the source index is a regex like blah*, we will get an empty response even if the index does not exist. This PR checks indices exist in the presence of empty search results. If yes, we throw an IndexNotFoundException that ends up being converted to EndRunException; if no, we still throw an IllegalArgumentException.
Testing done:
1. added unit tests
2. reproduced manually and verified the change fixed the issue.
For more information on following Developer …
=> Check if indices exist in the presence of empty search results

build.gradle, src/test/java/org/opensearch/ad/TestHelpers.java, src/test/java/org/opensearch/ad/transport/AnomalyDetectorJobActionTests.java, src/test/java/org/opensearch/ad/transport/DeleteAnomalyDetectorTests.java, src/test/java/org/opensearch/ad/transport/GetAnomalyDetectorTests.java, src/test/java/org/opensearch/ad/transport/SearchAnomalyDetectorInfoActionTests.java, src/test/java/org/opensearch/ad/transport/SearchAnomalyResultActionTests.java, src/test/java/org/opensearch/ad/transport/StopDetectorActionTests.java
Signed-off-by: Xun Zhang <xunzh@amazon.com>
Increase tests coverage for GetAnomalyDetectorTransportAction and remove it and subclasses from Jacoco exclusive list. 
=> add more unit tests for AD transport actions

.github/labeler.yml
Update labeler to default backports to `2.x` branch.
=> Update labeler to default backport to 2.x

build.gradle, src/main/java/org/opensearch/ad/ml/EntityColdStarter.java, src/main/java/org/opensearch/ad/transport/DeleteModelTransportAction.java, src/test/java/org/opensearch/ad/e2e/DetectionResultEvalutationIT.java, src/test/java/org/opensearch/ad/ml/EntityColdStarterTests.java, src/test/java/org/opensearch/ad/transport/DeleteModelTransportActionTests.java
backport https://github.com/opensearch-project/anomaly-detection/pull/460 and https://github.com/opensearch-project/anomaly-detection/pull/456 to 1.3 branch.
=> [Backport to 1.3] restart bug fix

src/main/java/org/opensearch/ad/feature/CompositeRetriever.java, src/main/java/org/opensearch/ad/transport/AnomalyResultTransportAction.java, src/test/java/org/opensearch/ad/transport/MultiEntityResultTests.java
* Check if indices exist in the presence of empty search results
Previously, CompositeRetriever throws an IllegalArgumentException in the presence of empty results, which gets translated to internal failure and increments AD failure count. When the source index is a regex like blah*, we will get an empty response even if the index does not exist. This PR checks indices exist in the presence of empty search results. If yes, we throw an IndexNotFoundException that ends up being converted to EndRunException; if no, we still throw an IllegalArgumentException.
Testing done:
1. added unit tests
2. reproduced manually and verified the change fixed the issue.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> [Backport to 1.3] Empty search results bug fix (#495)

src/main/java/org/opensearch/ad/transport/SearchAnomalyResultTransportAction.java, src/test/java/org/opensearch/ad/transport/SearchAnomalyResultActionTests.java
Signed-off-by: Xun Zhang <xunzh@amazon.com>
Refactor SearchAnomalyResultTransportAction to allow better unit test coverages. More tests added and coverage increased.
https://github.com/opensearch-project/anomaly-detection/issues/493
=> refactor SearchADResultTransportAction to be more testable

build.gradle
Fixing AD CI since build doesn't always have `-SNAPSHOT`.
#530
=> fixed to check if build is a snapshot

build.gradle, src/test/java/org/opensearch/ad/transport/handler/AnomalyResultBulkIndexHandlerTests.java
Increase test coverage and remove AnomalyResultBulkIndexHandler from the Jacoco exclusion list.
[_List any issues this PR will resolve, e.g. Closes [...]._ ](https://github.com/opensearch-project/anomaly-detection/issues/518)
=> Increase more coverage and reduce jacocoExclusions

build.gradle, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java
remove rc1 qualifier and use of `_type` in test as that field doesn't exist anymore for default index.
resolves #536 
=> remove rc1 qualifier 

src/main/java/org/opensearch/ad/ml/EntityColdStarter.java, src/main/java/org/opensearch/ad/ratelimit/CheckpointReadWorker.java, src/test/java/org/opensearch/ad/NodeStateManagerTests.java, src/test/java/org/opensearch/ad/ml/EntityColdStarterTests.java, src/test/java/org/opensearch/ad/ratelimit/CheckpointReadWorkerTests.java
Testing done:
Note: I found the bug in 1.2, so I started with 1.2 branch. Will forward push to 1.3 and 2.x later. …
=> Use current time as training data end time

src/main/java/org/opensearch/ad/ml/EntityColdStarter.java, src/main/java/org/opensearch/ad/ratelimit/CheckpointReadWorker.java, src/test/java/org/opensearch/ad/NodeStateManagerTests.java, src/test/java/org/opensearch/ad/ml/EntityColdStarterTests.java, src/test/java/org/opensearch/ad/ratelimit/CheckpointReadWorkerTests.java
* Use current time as training data end time
Testing done:
https://github.com/opensearch-project/anomaly-detection/issues/540 …
=> [Forward port to 2.0] Use current time as training data end time (#547)

src/main/java/org/opensearch/ad/ml/EntityColdStarter.java, src/main/java/org/opensearch/ad/ratelimit/CheckpointReadWorker.java, src/test/java/org/opensearch/ad/NodeStateManagerTests.java, src/test/java/org/opensearch/ad/ml/EntityColdStarterTests.java, src/test/java/org/opensearch/ad/ratelimit/CheckpointReadWorkerTests.java
* Use current time as training data end time
Testing done:
https://github.com/opensearch-project/anomaly-detection/issues/540 …
=> [Forward port to 2.x] Use current time as training data end time (#547)

src/main/java/org/opensearch/ad/ml/EntityColdStarter.java, src/main/java/org/opensearch/ad/ratelimit/CheckpointReadWorker.java, src/test/java/org/opensearch/ad/NodeStateManagerTests.java, src/test/java/org/opensearch/ad/ml/EntityColdStarterTests.java, src/test/java/org/opensearch/ad/ratelimit/CheckpointReadWorkerTests.java
* Use current time as training data end time
Testing done:
https://github.com/opensearch-project/anomaly-detection/issues/540 …
=> [Forward port to main] Use current time as training data end time (#547)

src/main/java/org/opensearch/ad/ml/EntityColdStarter.java, src/main/java/org/opensearch/ad/ratelimit/CheckpointReadWorker.java, src/test/java/org/opensearch/ad/NodeStateManagerTests.java, src/test/java/org/opensearch/ad/e2e/DetectionResultEvalutationIT.java, src/test/java/org/opensearch/ad/ml/EntityColdStarterTests.java, src/test/java/org/opensearch/ad/ratelimit/CheckpointReadWorkerTests.java
* Use current time as training data end time
Testing done:
https://github.com/opensearch-project/anomaly-detection/issues/540 …
=> [Forward port to 1.3] Use current time as training data end time (#547)

src/main/java/org/opensearch/ad/feature/AbstractRetriever.java, src/test/java/org/opensearch/ad/feature/NoPowermockSearchFeatureDaoTests.java
original PR: https://github.com/opensearch-project/anomaly-detection/pull/425
Previously, when writing a feature using filter aggregation, we failed with EndRunException: Failed to parse aggregation.. due to missing logic parsing the result.
This PR adds the parsing logic.
Testing done:
1. added unit tests
2. end-to-end testing.
=> [backport to 1.3] Support writing features using filter aggregation (#425)

build.gradle
Bump RCF version to 3.0-rc3. 
New RCF version has critical bug fix for AD.
=> bump rcf to 3.0-rc3

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/org/opensearch/ad/cluster/ClusterManagerEventListener.java, src/main/java/org/opensearch/ad/indices/AnomalyDetectionIndices.java, src/test/java/org/opensearch/ad/ODFERestTestCase.java, src/test/java/org/opensearch/ad/cluster/ClusterManagerEventListenerTests.java
updated gradle version to 7.4.2 and OS version to 2.1. Name changes on a few methods because of changes in core.
#578 
=> 2.1 version bump and Gradle bump

.github/workflows/CI.yml, build.gradle, release-notes/opensearch-anomaly-detection.release-notes-2.1.0.0.md, src/test/java/org/opensearch/ad/e2e/DetectionResultEvalutationIT.java, src/test/java/org/opensearch/ad/ml/EntityColdStarterTests.java
This PR adds an option flag to print logs during tests and turn on the flag in CI workflow. The flag is disabled by default. By doing this, we can record model accuracy metrics in git workflows and later retrieve it for analysis.
Testing done:
1. We can turn on/off logs during tests.
2. The accuracy logs are recorded.
=> Expose model accuracy metrics in tests

.github/workflows/CI.yml, build.gradle
bumped to 1.3.4
Changed fetching new AD version from gradle assemble instead of from ci.distribution.org
#586
=> Increment version to 1.3.4 and fix zip fetching

build.gradle
uses newest version snapshot from `gradle assemble` instead of ci.distribution.org in CI because of failure fetching during version increment
resolves #586 
=> fix zip fetching issue on version increment

build.gradle, src/test/java/org/opensearch/ad/bwc/ADBackwardsCompatibilityIT.java
Update BWC links to point to OpenSearch 1.1.0, since Open Distro is now officially unsupported. See OpenSearch [maintenance policy](https://opensearch.org/releases.html#maintenance-policy) on supported versions.
This PR also cleans up BWC tests to be compatible with 1.1 as the baseline. Note there was some changes to historical analysis between ODFE 1.13.0.0 (based on ES 7.10.2) => OpenSearch 1.1.0.0.
=> Update BWC zip links

build.gradle, src/test/java/test/org/opensearch/ad/util/FakeNode.java
Bump to 2.2.0.0.
Updates the `FakeNode` to include a `TaskResourceTrackingService` as required as part of [this change](https://github.com/opensearch-project/OpenSearch/pull/3982) backported into `2.x` branch on 8/2.
=> Bump version to 2.2

src/test/java/test/org/opensearch/ad/util/FakeNode.java
This [PR in OpenSearch](https://github.com/opensearch-project/OpenSearch/pull/4141) refactored the `TaskManager` which is overridden in `FakeNode` and was merged on 8/5. This fixes the compilation error as seen from [this GHA](https://github.com/opensearch-project/anomaly-detection/runs/7700323125?check_suite_focus=true)
=> Fix taskmanager compilation error in FakeNode

build.gradle, src/main/java/org/opensearch/ad/MemoryTracker.java, src/main/java/org/opensearch/ad/feature/SearchFeatureDao.java, src/main/java/org/opensearch/ad/ml/ModelManager.java, src/test/java/org/opensearch/ad/feature/SearchFeatureDaoTests.java, src/test/java/org/opensearch/ad/ml/ModelManagerTests.java, src/test/java/test/org/opensearch/ad/util/FakeNode.java
2.2 core added new dependencies of ClusterSettings like TaskResourceTrackingService. It is possible that the classloader that loads TaskResourceTrackingService is different from the classloader that loads PowerMock and related dependencies. PowerMock reports java.lang.NoClassDefFoundError when initializing ClusterSettings. Since we are not actually using the value of ClusterSettings in the tests, we make it null to avoid initializing it. The change fixed failed tests.
This PR also fixed spotless errors in FakeNode due to recent changes.
Testing done:
* gradle build
https://github.com/opensearch-project/anomaly-detection/issues/630 …
=> Fix PowerMock related tests due to version bump

build.gradle, src/test/java/org/opensearch/ad/feature/SearchFeatureDaoTests.java, src/test/java/org/opensearch/ad/ml/ModelManagerTests.java, src/test/java/test/org/opensearch/ad/util/FakeNode.java
To integrate SDK with AD plugin, AD has to build with 3.0 OpenSearch as SDK is using the same. This PR adds that.
This also removes the dependency on Job Scheduler as JS is not available on `https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/` because the `main` branch of JS is still on `2.2.0-SNAPSHOT`
Part of https://github.com/opensearch-project/opensearch-sdk-java/issues/24
=> [Feature/extensions] Build AD with OpenSearch 3.0 

build.gradle, src/test/java/org/opensearch/ad/bwc/ADBackwardsCompatibilityIT.java
Since Opendistro has now been depreciated, this PR removed links to older opendistro zips and changed them to OS 1.1 for purposes of BWC. Also includes test changes to accommodate for new change in bwc not pointing to opendistro anymore.
This PR also includes a change to a historical analysis test to accommodate changes in bwc for 1.1.0 as also done in this PR: https://github.com/opensearch-project/anomaly-detection/pull/625
=> [1.3] Fixing 1.3.x BWC CI

src/main/java/org/opensearch/ad/cluster/ClusterManagerEventListener.java, src/main/java/org/opensearch/ad/indices/AnomalyDetectionIndices.java, src/test/java/org/opensearch/ad/cluster/ADClusterEventListenerTests.java, src/test/java/org/opensearch/ad/cluster/ClusterManagerEventListenerTests.java, src/test/java/test/org/opensearch/ad/util/ClusterCreation.java
This PR removes additional uses of the term "master" from the code. Additional removals will occur after more updates are made on OS core.
=> Removed additional non-inclusive terms 

README.md
Signed-off-by: cwillum <cwmmoore@amazon.com>
Replace the link to Forum discussion in the README.md file so that it points to the OpenSearch forum rather than the defunct Open Distro forum.
This fixes the issue for the Anomaly Detection plugin in [#921](https://github.com/opensearch-project/documentation-website/issues/921).
=> Replace Forum link in Anomaly Detection plugin README.md

build.gradle
Add support for reproducible builds
As per gradle [docs] add support to remove timestamps and package with same order which is required from
[reproducible] builds
[docs]: https://docs.gradle.org/current/userguide/working_with_files.html#sec:archives
[reproducible]: https://reproducible-builds.org/
N/A
=> Add support for reproducible builds

src/test/java/org/opensearch/ad/e2e/DetectionResultEvalutationIT.java
Changed integration test so it doesn't default to exact window delay that assumes creation of data and test run time is in a few seconds. When I ran this test on my mac, the test took longer to run meaning more time has passed between the data creation and the validate API call. 
Meaning that it would fail with something like, "expected window delay to be 4 minutes but got 6 minutes if test took 2 minutes longer". I am not 100% sure why my macbook was so slow for this test where it didn't even fail on the github CI runner but regardless new logic makes more sense.
However with this fixed we can now, run, test and build AD on macos. 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> Fix window delay test

.github/workflows/CI.yml, build.gradle, src/main/java/org/opensearch/ad/AnomalyDetectorExtension.java, src/main/java/org/opensearch/ad/rest/RestCreateDetectorAction.java, src/main/resources/ad-extension.yml
This PR makes the extension run independently and removes the dependency on `opensearchplugin`. For now tasks such as `publishing` and `bundlePlugin` are taken care of. `integTest` will be done by creating a new framework for integration tests here https://github.com/opensearch-project/opensearch-sdk-java/issues/120. The remaining tasks are P1 and will be done in https://github.com/opensearch-project/opensearch-sdk-java/issues/144.
It also integrates the local published SDK with AD build.gradle and has a main class to run the extension from. 
For now, the sample RestHandler is integrated but later with https://github.com/opensearch-project/opensearch-sdk-java/issues/58 it will be replaced with create Index.
Companion PR on OpenSearch: …
=> [Feature/extensions] Removed opensearchplugin and extension runs independently

build.gradle
=> update jackson dependency version

build.gradle
backport https://github.com/opensearch-project/anomaly-detection/pull/678 to 1.3, auto backport PR failed
#676 
=> [backport 1.3] update jackson dependency version (#678)

src/main/java/org/opensearch/ad/AnomalyDetectorExtension.java, src/main/java/org/opensearch/ad/rest/RestCreateDetectorAction.java, src/main/java/org/opensearch/ad/transport/ADCancelTaskNodeRequest.java, src/main/java/org/opensearch/ad/transport/ADStatsNodeRequest.java, src/main/java/org/opensearch/ad/transport/ADTaskProfileNodeRequest.java, src/main/java/org/opensearch/ad/transport/CronNodeRequest.java, src/main/java/org/opensearch/ad/transport/DeleteModelNodeRequest.java, src/main/java/org/opensearch/ad/transport/ProfileNodeRequest.java, src/test/java/org/opensearch/ad/mock/transport/MockADCancelTaskNodeRequest_1_0.java
Copies the `getSettings()` method impelmentation from `AnomalyDetectorPlugin` to `AnomalyDetectorExtension`.  This is the third and final step to complete work already done in [SDK #147](https://github.com/opensearch-project/opensearch-sdk-java/pull/147) and and [OS #4519](https://github.com/opensearch-project/OpenSearch/pull/4519) register AD settings with OpenSearch
Fixes [SDK #159](https://github.com/opensearch-project/opensearch-sdk-java/issues/159)
Relates to [SDK #132](https://github.com/opensearch-project/opensearch-sdk-java/issues/132) …
=> [Feature/extensions] Add getSettings support for AD

.github/workflows/CI.yml, src/test/java/org/opensearch/ad/ml/CheckpointDaoTests.java
Adds windows CI for main branch
1. Changed the usage of getPath() to first use .toURI() in some of the test cases. This is because just getting the path like we used to was returning a string like this:` \C:\Sample\sample.txt`. This isn't supported on Windows. Converting with `toUri()` works on all platforms.
resolves #274 
=> windows CI for AD

src/main/java/org/opensearch/ad/AnomalyDetectorExtension.java, src/main/java/org/opensearch/ad/rest/RestCreateDetectorAction.java, src/main/resources/ad-extension.yml
Randomized detector id for create/get detector
Currently the detector id for create/get detector is not randomized and is a pure string in the response of create detector
```
{
"id": "1",
"version": 1,
```
Changed it to
```
{
"_id": "VEHKTXwBwf_U8gjUXY2s",
"_version": 1,
```
Closes https://github.com/opensearch-project/opensearch-sdk-java/issues/212
=> [Feature/extensions] Randomized detector id for create/get detector

src/main/java/org/opensearch/ad/AnomalyDetectorExtension.java, src/main/java/org/opensearch/ad/rest/RestGetDetectorAction.java
Signed-off-by: Frank Lou <mloufra@amazon.com>
Create an action implementing `ExtensionRestHandler` with routes for the get detector API calls.
Fixes https://github.com/opensearch-project/opensearch-sdk-java/issues/213
=> [Feature/extensions] Add Action for Get detector API call

.github/workflows/benchmark.yml, DEVELOPER_GUIDE.md, build.gradle, src/test/java/org/opensearch/ad/e2e/SingleStreamModelPerfIT.java, src/test/java/org/opensearch/ad/ml/AbstractCosineDataTest.java, src/test/java/org/opensearch/ad/ml/EntityColdStarterTests.java, src/test/java/org/opensearch/ad/ml/HCADModelPerfTests.java, src/test/java/org/opensearch/ad/util/LabelledAnomalyGenerator.java, src/test/java/org/opensearch/ad/util/MultiDimDataWithTime.java
This PR adds an AD model performance benchmark so that we can compare model performance across versions.
For the single stream detector, we refactored tests in DetectionResultEvalutationIT and moved it to SingleStreamModelPerfIT.
For the HCAD detector, we randomly generated synthetic data with known anomalies inserted throughout the signal. In particular, these are one/two/four dimensional data where each dimension is a noisy cosine wave. Anomalies are inserted into one dimension with 0.003 probability. Anomalies across each dimension can be independent or dependent. We have approximately 5000 observations per data set. The data set is generated using the same random seed so the result is comparable across versions.
We also backported #600 so that we can capture the performance data in CI …
=> AD model performance benchmark

src/main/java/org/opensearch/ad/rest/RestCreateDetectorAction.java
NOTE: Requires merging [SDK #246](https://github.com/opensearch-project/opensearch-sdk-java/pull/246/files) first.
Simplifies `CreateDetectorAction` by extending `BaseExtensionRestHandler`:
- changes `routes()` to `routeHandlers()` which auto-checks the method and path
- removes the unnecessary check for the method and path
- renames the handler method to avoid name conflict/override
Fixes [SDK #245](https://github.com/opensearch-project/opensearch-sdk-java/issues/245)
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificat …
=> [Feature/extensions] CreateDetectorAction extends BaseExtensionRestHandler

src/main/java/org/opensearch/ad/AnomalyDetectorExtension.java, src/main/java/org/opensearch/ad/rest/RestValidateDetectorAction.java
Signed-off-by: Frank Lou <mloufra@amazon.com>
Create an action implementing `ExtensionRestHandler` with routes for the Post detector API calls.
Fixes https://github.com/opensearch-project/opensearch-sdk-java/issues/221
=> [Feature/extensions] Add Action for Validate detector API call

src/main/java/org/opensearch/ad/util/RestHandlerUtils.java
OpenSearch removed `coalesceToEmpty` in this [PR](https://github.com/opensearch-project/OpenSearch/pull/5288). Adding it for the AD plugin.
=> Added coalesceToEmpty method

.github/workflows/benchmark.yml, DEVELOPER_GUIDE.md, build.gradle, src/test/java/org/opensearch/ad/e2e/AbstractSyntheticDataTest.java, src/test/java/org/opensearch/ad/e2e/DetectionResultEvalutationIT.java, src/test/java/org/opensearch/ad/e2e/SingleStreamModelPerfIT.java, src/test/java/org/opensearch/ad/ml/AbstractCosineDataTest.java, src/test/java/org/opensearch/ad/ml/EntityColdStarterTests.java, src/test/java/org/opensearch/ad/ml/HCADModelPerfTests.java, src/test/java/test/org/opensearch/ad/util/LabelledAnomalyGenerator.java
This PR adds an AD model performance benchmark so that we can compare model performance across versions.
Regarding benchmark data, we randomly generated synthetic data with known anomalies inserted throughout the signal. In particular, these are one/two/four dimensional data where each dimension is a noisy cosine wave. Anomalies are inserted into one dimension with 0.003 probability. Anomalies across each dimension can be independent or dependent. We have approximately 5000 observations per data set. The data set is generated using the same random seed so the result is comparable across versions.
We also backported #600 so that we can capture the performance data in CI output.
Testing done:
* added unit tests to run the benchmark.
By submitting …
=> AD model performance benchmark (#729)

src/main/java/org/opensearch/ad/AnomalyDetectorExtension.java, src/main/java/org/opensearch/ad/model/ModelProfile.java, src/main/java/org/opensearch/ad/rest/RestValidateDetectorAction.java, src/test/java/org/opensearch/ad/model/ModelProfileTests.java
Signed-off-by: Varun Jain <varunudr@amazon.com>
Template of Handle Validate Detector request in RestValidateDetectorAction
Part of Issue: 
[https://github.com/opensearch-project/opensearch-sdk-java/issues/222](https://github.com/opensearch-project/opensearch-sdk-java/issues/222)
=> [Feature/extensions] Validate Detector Action Handle request

src/test/java/org/opensearch/ad/model/ModelProfileTests.java
Signed-off-by: Varun Jain <varunudr@amazon.com>
Adding Model Profile Tests
=> Model Profile Test

src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/main/java/org/opensearch/ad/rest/AbstractSearchAction.java, src/main/java/org/opensearch/ad/rest/RestSearchAnomalyResultAction.java, src/main/java/org/opensearch/ad/util/RestHandlerUtils.java, src/test/java/org/opensearch/ad/util/RestHandlerUtilsTests.java
Enable the use of _source for search anomaly detectors, anomaly results and detector task search queries so specific fields can be included/excluded.
Previously we re-parsed the anomaly detector object before sending back the search response in order to keep the order of the response which gets re-arranged when we exclude something like `ui_metadata`.
JSON response before making this change:
```
{
"_index": ".opendistro-anomaly-detectors",
"_id": "v80i6YQBbB0CCcTBFrmD",
"_version": 1,
"_seq_no": 0,
"_primary_term": 1,
"_score": 1.0,
"_source": {
"name": "sample-http-responses-detector",
"description": "A sample detector to detect anomalies with HTTP response code logs.",
"time_field": "timestamp",
"indices": [
"sample-http-responses"
],
"filter_query": {
"match_all": {
"boost": 1.0
}
}, …
```
=> Fix _source bug

MAINTAINERS.md
Signed-off-by: dblock <dblock@amazon.com>
Fix: typo in ohltyler.
=> Fix: typo in ohltyler.

src/main/java/org/opensearch/ad/AnomalyDetectorJobRunner.java, src/main/java/org/opensearch/ad/AnomalyDetectorPlugin.java, src/main/java/org/opensearch/ad/ExecuteADResultResponseRecorder.java, src/main/java/org/opensearch/ad/caching/PriorityCache.java, src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/main/java/org/opensearch/ad/ratelimit/EntityColdStartWorker.java, src/main/java/org/opensearch/ad/rest/RestExecuteAnomalyDetectorAction.java, src/main/java/org/opensearch/ad/rest/handler/IndexAnomalyDetectorJobActionHandler.java, src/main/java/org/opensearch/ad/settings/EnabledSetting.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/ad/transport/AnomalyDetectorJobTransportAction.java, src/main/java/org/opensearch/ad/transport/AnomalyResultTransportAction.java, src/test/java/org/opensearch/ad/AnomalyDetectorJobRunnerTests.java, src/test/java/org/opensearch/ad/ODFERestTestCase.java, src/test/java/org/opensearch/ad/caching/PriorityCacheTests.java, src/test/java/org/opensearch/ad/e2e/DetectionResultEvalutationIT.java, src/test/java/org/opensearch/ad/ml/EntityColdStarterTests.java, src/test/java/org/opensearch/ad/mock/transport/MockAnomalyDetectorJobTransportActionWithUser.java, src/test/java/org/opensearch/ad/ratelimit/EntityColdStartWorkerTests.java, src/test/java/org/opensearch/ad/rest/handler/IndexAnomalyDetectorJobActionHandlerTests.java, src/test/java/org/opensearch/ad/transport/AnomalyDetectorJobActionTests.java
If historical data is enough, a single stream detector takes 1 interval for cold start to be triggered + 1 interval for the state document to be updated. Similar to single stream detectors, HCAD cold start needs 2 intervals and one more interval to make sure an entity appears more than once. So HCAD needs three intervals to complete cold starts. Long initialization is the single most complained problem of AD. This PR reduces both single stream and HCAD detectors' initialization time to 1 minute by
* delaying real time cache update by one minute when we receive ResourceNotFoundException in single stream detectors or when the init progress of HCAD real time cache is 0. Thus, we can finish the cold start and writing checkpoint one minute later and update the state document accordingly. This …
=> Speed up cold start

build.gradle, src/main/java/org/opensearch/ad/AnomalyDetectorJobRunner.java, src/main/java/org/opensearch/ad/AnomalyDetectorPlugin.java, src/main/java/org/opensearch/ad/ExecuteADResultResponseRecorder.java, src/main/java/org/opensearch/ad/caching/PriorityCache.java, src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/main/java/org/opensearch/ad/ratelimit/EntityColdStartWorker.java, src/main/java/org/opensearch/ad/rest/RestExecuteAnomalyDetectorAction.java, src/main/java/org/opensearch/ad/rest/handler/IndexAnomalyDetectorJobActionHandler.java, src/main/java/org/opensearch/ad/settings/EnabledSetting.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/ad/transport/AnomalyDetectorJobTransportAction.java, src/main/java/org/opensearch/ad/transport/AnomalyResultTransportAction.java, src/test/java/org/opensearch/ad/AnomalyDetectorJobRunnerTests.java, src/test/java/org/opensearch/ad/caching/PriorityCacheTests.java, src/test/java/org/opensearch/ad/e2e/DetectionResultEvalutationIT.java, src/test/java/org/opensearch/ad/ml/EntityColdStarterTests.java, src/test/java/org/opensearch/ad/mock/transport/MockAnomalyDetectorJobTransportActionWithUser.java, src/test/java/org/opensearch/ad/ratelimit/EntityColdStartWorkerTests.java, src/test/java/org/opensearch/ad/rest/handler/IndexAnomalyDetectorJobActionHandlerTests.java, src/test/java/org/opensearch/ad/transport/AnomalyDetectorJobActionTests.java
If historical data is enough, a single stream detector takes 1 interval for cold start to be triggered + 1 interval for the state document to be updated. Similar to single stream detectors, HCAD cold start needs 2 intervals and one more interval to make sure an entity appears more than once. So HCAD needs three intervals to complete cold starts. Long initialization is the single most complained problem of AD. This PR reduces both single stream and HCAD detectors' initialization time to 1 minute by
* delaying real time cache update by one minute when we receive ResourceNotFoundException in single stream detectors or when the init progress of HCAD real time cache is 0. Thus, we can finish the cold start and writing checkpoint one minute later and update the state document accordingly. This …
=> [Backport to 2.x] Speed up cold start (#753)

build.gradle, src/main/java/org/opensearch/ad/AnomalyDetectorJobRunner.java, src/main/java/org/opensearch/ad/AnomalyDetectorPlugin.java, src/main/java/org/opensearch/ad/AnomalyDetectorProfileRunner.java, src/main/java/org/opensearch/ad/ExecuteADResultResponseRecorder.java, src/main/java/org/opensearch/ad/ProfileUtil.java, src/main/java/org/opensearch/ad/task/ADRealtimeTaskCache.java, src/main/java/org/opensearch/ad/task/ADTaskCacheManager.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/test/java/org/opensearch/ad/AbstractADTest.java, src/test/java/org/opensearch/ad/AnomalyDetectorJobRunnerTests.java, src/test/java/org/opensearch/ad/rest/handler/IndexAnomalyDetectorJobActionHandlerTests.java, src/test/java/org/opensearch/ad/task/ADTaskCacheManagerTests.java, src/test/java/org/opensearch/ad/task/ADTaskManagerTests.java, src/test/java/org/opensearch/ad/transport/ADBatchAnomalyResultTransportActionTests.java
This PR fixes the discrepancy by querying the result index when the total updates is less than 32. We have done similar things in profile API so I refactored reusable code to ProfileUtil. We also cached whether we have queried the result index and won't repeatedly issue the extra query.
Testing done:
1. repeated repro steps in https://github.com/opensearch-project/anomaly-detection/issues/502 and verified the issue has been resolved.
2. added unit tests.
https://github.com/opensearch-project/anomaly-detection/issues/502 …
=> Fix the discrepancy between Profile API and real time tasks API

src/main/java/org/opensearch/ad/AnomalyDetectorJobRunner.java, src/main/java/org/opensearch/ad/AnomalyDetectorPlugin.java, src/main/java/org/opensearch/ad/AnomalyDetectorProfileRunner.java, src/main/java/org/opensearch/ad/ExecuteADResultResponseRecorder.java, src/main/java/org/opensearch/ad/ProfileUtil.java, src/main/java/org/opensearch/ad/constant/CommonName.java, src/main/java/org/opensearch/ad/task/ADRealtimeTaskCache.java, src/main/java/org/opensearch/ad/task/ADTaskCacheManager.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/test/java/org/opensearch/ad/AbstractADTest.java, src/test/java/org/opensearch/ad/AnomalyDetectorJobRunnerTests.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/rest/handler/IndexAnomalyDetectorJobActionHandlerTests.java, src/test/java/org/opensearch/ad/task/ADTaskCacheManagerTests.java, src/test/java/org/opensearch/ad/task/ADTaskManagerTests.java, src/test/java/org/opensearch/ad/transport/ADBatchAnomalyResultTransportActionTests.java
https://github.com/opensearch-project/anomaly-detection/pull/770
=> [backport to 2.5] Fix the discrepancy between Profile API and real time tasks API

src/main/java/org/opensearch/ad/AnomalyDetectorJobRunner.java, src/main/java/org/opensearch/ad/AnomalyDetectorPlugin.java, src/main/java/org/opensearch/ad/AnomalyDetectorProfileRunner.java, src/main/java/org/opensearch/ad/ExecuteADResultResponseRecorder.java, src/main/java/org/opensearch/ad/ProfileUtil.java, src/main/java/org/opensearch/ad/constant/CommonName.java, src/main/java/org/opensearch/ad/task/ADRealtimeTaskCache.java, src/main/java/org/opensearch/ad/task/ADTaskCacheManager.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/test/java/org/opensearch/ad/AbstractADTest.java, src/test/java/org/opensearch/ad/AnomalyDetectorJobRunnerTests.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/rest/handler/IndexAnomalyDetectorJobActionHandlerTests.java, src/test/java/org/opensearch/ad/task/ADTaskCacheManagerTests.java, src/test/java/org/opensearch/ad/task/ADTaskManagerTests.java, src/test/java/org/opensearch/ad/transport/ADBatchAnomalyResultTransportActionTests.java
https://github.com/opensearch-project/anomaly-detection/pull/770
=> [backport to 2.x] Fix the discrepancy between Profile API and real time tasks API

build.gradle
We need to bump the version because only the latest 2.x will be upgradable to 3.0 when that ships. Since OpenSearch core bumped to 2.6, we need to do that as well. Note after bumping version, bwc still fails to find 2.6.0 core zip.
=> bump bwc to 2.6.0

build.gradle
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
As currently 2.x is bumped to 2.6, we should have also increment the version for bwc tests. 
Instead, this PR is to dynamically set bwc current version from properties version so we don't have to change this version every time we do version increment. 
Will also need to backport this PR to 2.5 branch. 
Part of https://github.com/opensearch-project/opensearch-build/issues/2870
=> Dynamically set bwc current version from properties version

src/main/java/org/opensearch/ad/ExecuteADResultResponseRecorder.java, src/main/java/org/opensearch/ad/constant/CommonErrorMessages.java, src/main/java/org/opensearch/ad/transport/AnomalyResultTransportAction.java, src/test/java/org/opensearch/ad/rest/handler/IndexAnomalyDetectorJobActionHandlerTests.java
We used to log "No RCF models are available either because RCF models are not ready..." and now we log "resource_not_found_exception: No checkpoints found for model id...". This change caused an integration test failure. This PR reverts it back.
Testing done:
1. verified that the original log is back.
=> Revert changes to exception message

build.gradle, src/main/java/org/opensearch/ad/AnomalyDetectorExtension.java, src/main/java/org/opensearch/ad/AnomalyDetectorPlugin.java, src/main/java/org/opensearch/ad/MemoryTracker.java, src/main/java/org/opensearch/ad/task/ADTaskCacheManager.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/test/java/org/opensearch/ad/MemoryTrackerTests.java, src/test/java/org/opensearch/ad/caching/PriorityCacheTests.java, src/test/java/org/opensearch/ad/ml/ModelManagerTests.java, src/test/java/org/opensearch/ad/task/ADTaskCacheManagerTests.java
Implementing create components, commented associated test classes for components until `SDKClusterSettings` support is added.
Part of : https://github.com/opensearch-project/opensearch-sdk-java/issues/499
=> [Feature/extensions] Implements create components for AnomalyDetectionIndices and ADTaskManager

src/main/java/org/opensearch/ad/AnomalyDetectorExtension.java, src/main/java/org/opensearch/ad/rest/RestGetAnomalyDetectorAction.java, src/main/java/org/opensearch/ad/rest/RestIndexAnomalyDetectorAction.java, src/main/java/org/opensearch/ad/rest/RestValidateAnomalyDetectorAction.java
Moves rest client instantiation to create components, which ensures that only one instance of the SDKRestClient is being passed around
=> [Feature/extension] Moved rest client instantiation to constructor

src/main/java/org/opensearch/ad/AnomalyDetectorExtension.java
Updates the `AnomalyDetectorExtension` class:
- BaseExtension no longer implements `ActionExtension` so that was added, otherwise the `@Override` annotation on `getExtensionRestHandlers()` was broken.
- Fixes initialization of RestClient and AsyncClient to always use the same (initialized) SDKClient instance
- Removes the ExtensionSettings parameter, which will be removed in [SDK #579](https://github.com/opensearch-project/opensearch-sdk-java/pull/579)
Part of [SDK #556](https://github.com/opensearch-project/opensearch-sdk-java/pull/579) but fixes things broken from previous merges.
For more information on following Developer Certificate of Origin and signing off your …
=> [Feature/extensions] Update initialization of SDK Clients

src/main/java/org/opensearch/ad/AnomalyDetectorExtension.java, src/test/java/org/opensearch/ad/feature/NoPowermockSearchFeatureDaoTests.java, src/test/java/org/opensearch/ad/feature/SearchFeatureDaoTests.java, src/test/java/org/opensearch/ad/indices/CustomIndexTests.java, src/test/java/org/opensearch/ad/indices/InitAnomalyDetectionIndicesTests.java, src/test/java/org/opensearch/ad/indices/RolloverTests.java
Updates tests which needed SDKClusterSettings instantiated with a list of settings following merge of [SDK #559](https://github.com/opensearch-project/opensearch-sdk-java/pull/559).
Fixes [SDK #503](https://github.com/opensearch-project/opensearch-sdk-java/issues/503)
=> [Feature/Extensions] Use parameterized SDKClusterSettings in tests

src/main/java/org/opensearch/ad/rest/RestGetAnomalyDetectorAction.java, src/main/java/org/opensearch/ad/rest/RestIndexAnomalyDetectorAction.java, src/main/java/org/opensearch/ad/rest/RestValidateAnomalyDetectorAction.java
Companion PRs (this one must be merged after Core and SDK):
- Core: https://github.com/opensearch-project/OpenSearch/pull/6874
- SDK: https://github.com/opensearch-project/opensearch-sdk-java/pull/623
Extensions do not use all the internal components of a `RestRequest` and initial implementation double-purposed the `ExtensionsRestRequest` object used in transport as the object that Extensions would need to handle.  However, increasing use of the methods on this object are ending up duplicating a lot of code.  It makes a lot more sense to just recreate a `RestRequest` object from the parameters passed in this request.
Part of [SDK #431](https://github.com/opensearch-project/opensearch-sdk-java/issues/431).
By submitting this pull request, I confirm that my contribution is made under the …
=> [Feature/extensions] Update Rest handlers to use RestRequest

src/main/java/org/opensearch/ad/transport/handler/ADSearchHandler.java, src/main/java/org/opensearch/ad/util/ParseUtils.java, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java, src/test/java/org/opensearch/ad/util/ParseUtilsTests.java
Prioritizing admin role over backend role filtering for all AD operations.
Validated manually that admins can now perform all AD APIs on given detector even if the backend roles don't match. Also if an admin updates a detector, it won't rewrite the backend role.
Security tests pass against a 2.6 cluster, 3.0 distribution has other issues that are being solved by other plugins.
resolves #842 
=> Giving admin priority over backendrole filtering

src/main/java/org/opensearch/ad/transport/handler/ADSearchHandler.java, src/main/java/org/opensearch/ad/util/ParseUtils.java, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java, src/test/java/org/opensearch/ad/util/ParseUtilsTests.java
=> [Backport 2.7] Giving admin priority over backendrole filtering (#850)

dataGeneration/generate-cosine-data-multi-entity.py, src/main/java/org/opensearch/ad/rest/handler/AbstractAnomalyDetectorActionHandler.java
Adds field mapping validation check for validate detector API .
note : Valid detector/model configuration returns an empty response : `{}`
**Validate Single Entity Detector (valid detector)**
```
curl -X POST "localhost:9200/_extensions/_ad-extension/detectors/_validate" -H "Content-Type:application/json" --data
'{
"name": "test-detector",
"description": "Test detector",
"time_field": "@timestamp",
"indices": [
"server_log"
],
"feature_attributes": [
{
"feature_name": "test",
"feature_enabled": true,
"aggregation_query": {
"test": {
"avg": {
"field": "jvmGcTime"
}
}
}
}
],
"detection_interval": {
"period": {
"interval": 1,
"unit": "Minutes"
}
},
"window_delay": {
"period": {
"interval": 1,
"unit": "Minutes"
}
}
}'
{}
```
**Validate Single Entity Detector (invalid detector mapping : time …
=> [Extensions] Replaces ADTransportGetFieldsMappingsAction with SDK indices client call

.github/CODEOWNERS, MAINTAINERS.md
Sync up CODEOWNERS with MAINTAINERS.md.
Moved @zhanghg08 and @yizheliu-amazon to emeritus as they aren't members of the org anymore.
Closes #808.
=> Sync up CODEOWNERS with MAINTAINERS.md.

src/main/java/org/opensearch/ad/indices/AnomalyDetectionIndices.java, src/main/java/org/opensearch/ad/rest/handler/AnomalyDetectorActionHandler.java, src/main/java/org/opensearch/ad/transport/DeleteAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/ad/transport/StatsAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/ad/util/IndexUtils.java, src/main/java/org/opensearch/ad/util/ParseUtils.java, src/test/java/org/opensearch/ad/indices/InitAnomalyDetectionIndicesTests.java
Companion SDK PR : https://github.com/opensearch-project/opensearch-sdk-java/pull/802 (SDK PR must be merged first)
Replaces the following cluster state calls to check if an index/alias exists with the `SDKIndicesClient` `exist()` and `existsAlias()` methods :
- `state().getRoutingTable().hasIndex(indexName)`
- `state().metadata().hasIndex(indexName)`
- `state().metadata().indices().containsKey(indexName)`
- `state().metadata().hasAlias(alias)` 
Part of https://github.com/opensearch-project/opensearch-sdk-java/issues/674 …
=> [Extensions] Improves performance by replacing cluster state calls for index existence with exists()/aliasExists() API calls

src/main/java/org/opensearch/ad/rest/RestAnomalyDetectorJobAction.java, src/main/java/org/opensearch/ad/rest/RestIndexAnomalyDetectorAction.java, src/main/java/org/opensearch/ad/transport/ADBatchAnomalyResultTransportAction.java, src/main/java/org/opensearch/ad/transport/AnomalyDetectorJobTransportAction.java, src/main/java/org/opensearch/ad/transport/AnomalyResultTransportAction.java, src/main/java/org/opensearch/ad/transport/DeleteAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/ad/transport/ForwardADTaskTransportAction.java, src/main/java/org/opensearch/ad/transport/GetAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/ad/transport/IndexAnomalyDetectorTransportAction.java, src/test/java/org/opensearch/ad/transport/ForwardADTaskTransportActionTests.java, src/test/java/org/opensearch/ad/transport/GetAnomalyDetectorTransportActionTests.java, src/test/java/org/opensearch/ad/transport/IndexAnomalyDetectorTransportActionTests.java
Coming from changes in https://github.com/opensearch-project/opensearch-sdk-java/pull/768
Retrieves transport service from SDKTransportService rather than directly from the extensionsRunner
=> [Extensions] Retrieve transport service from SDKTransportService rather than ExtensionsRunner

src/main/java/org/opensearch/ad/transport/ADCancelTaskTransportAction.java, src/main/java/org/opensearch/ad/transport/ADStatsNodesTransportAction.java, src/main/java/org/opensearch/ad/transport/ADTaskProfileTransportAction.java, src/main/java/org/opensearch/ad/transport/DeleteModelTransportAction.java, src/main/java/org/opensearch/ad/transport/ProfileTransportAction.java, src/test/java/org/opensearch/ad/transport/DeleteModelTransportActionTests.java
SDK Companion PR : https://github.com/opensearch-project/opensearch-sdk-java/pull/818 (SDK PR must be merged first)
Retrieves cluster name from the SDKClusterService rather than from the cluster state
See comment [here](https://github.com/opensearch-project/opensearch-sdk-java/issues/674#issuecomment-1581621293) for more details
Part of https://github.com/opensearch-project/opensearch-sdk-java/issues/674
=> [Extensions] Improves performance by replacing cluster state calls to retrieve cluster name

.github/CODEOWNERS, MAINTAINERS.md
Update outdated MAINTAINERS and OWNERS list
=> Updated Maintainers and CODE_OWNERS list

src/main/java/org/opensearch/ad/common/exception/NotSerializedADExceptionName.java, src/main/java/org/opensearch/ad/util/IndexUtils.java
Fixes imports due to changes upstream : https://github.com/opensearch-project/OpenSearch/pull/8035
Resolves AD stats API issue with null indices from Cluster health request by setting the cluster health request level to `indices`
Logs from testing stats API after creating a detector
```
dev-dsk-jpalis-2c-27c8aa11 % curl -XPOST "localhost:9200/_extensions/_ad-extension/detectors?pretty" -H "Content-Type:application/json" --data '{"name":"test-detector","description":"Test detector","time_field":"@timestamp","indices":["server_log"],"feature_attributes":[{"feature_name":"test","feature_enabled":true,"aggregation_query":{"test":{"avg":{"field":"jvmGcTime"}}}}],"detection_interval":{"period":{"interval":1,"unit":"Minutes"}},"window_delay":{"period":{"interval":1,"unit":"Minutes"}}}'
{
"_id": …
```
=> [Extensions] Fixing BaseException imports and fixing Cluster Index Health request

build.gradle
=> Bump guava version to 32.0.1

src/main/java/org/opensearch/ad/indices/ADIndexManagement.java, src/main/java/org/opensearch/forecast/indices/ForecastIndexManagement.java, src/main/java/org/opensearch/forecast/settings/ForecastSettings.java, src/main/java/org/opensearch/timeseries/indices/IndexManagement.java
In this PR, we temporarily enforce DOCUMENT replication for AD indices. This change is necessary due to the current limitation of SegRep, which doesn't support Get/MultiGet by ID. This measure will be in place until SegRep adds support for these operations.
This adjustment aligns with the modification made in the referenced PR: https://github.com/opensearch-project/job-scheduler/pull/417
Additionally, this PR increases the number of primary shards for forecasting indices from 10 to 20, recognizing the higher write intensity of these indices. For instance, when the horizon is 24, we are expected to save 25 documents: 24 for each forecast and 1 for the actual value. In contrast, for AD, we save one document per actual value.
Testing done:
1. gradle build passed …
=> Enforce DOCUMENT Replication for AD Indices and Adjust Primary Shards

release-notes/opensearch-anomaly-detection.release-notes-2.9.0.0.md
=> Add 2.9 release notes

src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/e2e/AbstractSyntheticDataTest.java, src/test/java/org/opensearch/ad/model/EntityProfileTests.java, src/test/java/org/opensearch/ad/model/ModelProfileTests.java, src/test/java/org/opensearch/ad/transport/ADStatsTests.java, src/test/java/org/opensearch/ad/transport/AnomalyResultTests.java, src/test/java/org/opensearch/ad/transport/CronTransportActionTests.java, src/test/java/org/opensearch/ad/transport/DeleteModelTransportActionTests.java, src/test/java/org/opensearch/ad/transport/DeleteTests.java, src/test/java/org/opensearch/ad/transport/EntityResultTransportActionTests.java, src/test/java/org/opensearch/ad/transport/ProfileTests.java, src/test/java/org/opensearch/ad/transport/RCFResultTests.java, src/test/java/org/opensearch/ad/transport/StopDetectorActionTests.java, src/test/java/org/opensearch/ad/transport/ThresholdResultTests.java
This is a follow-up to #971, where commit 2839bc2c6f470639b68901086c80cb2152d96558 only fixed _some_ but not _all_ of the build errors (it allowed `./gradlew run` to pass but `./gradlew build` was failing).
Fix the build errors when we run `./gradlew build`.
=> Fix build with latest OpenSearch (for real this time)

src/main/java/org/opensearch/ad/model/AnomalyResult.java
Manual Backport of https://github.com/opensearch-project/anomaly-detection/pull/976 (without the import changes since these were already handled by #974 )
=> [Backport 2.x] Defaults anomaly grade to 0 if negative

.github/workflows/auto-release.yml
Adds auto-release github workflow to automatically publish releases on Github using the release notes associated with the tag in the release-notes directory
Fixes https://github.com/opensearch-project/anomaly-detection/issues/807
=> Adds auto release workflow

build.gradle
Found this version conflict issue in recent build, adding this line to force commons-lang3 to use 3.12.0
```
* What went wrong:
Could not determine the dependencies of task ':thirdPartyAudit'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
> Conflict found for the following module:
- org.apache.commons:commons-lang3 between versions 3.13.0 and 3.12.0
```
=> upgrading commons-lang3 version to fix conflict issue

build.gradle, src/main/java/org/opensearch/ad/indices/AnomalyDetectionIndices.java
Backport #1012 to 2.x. 
Previous revert change is included in this backport pr because it was manually triggered as a separate pr. 
=> [Backport to 2.x] upgrading commons-lang3 version to fix conflict issue

build.gradle, src/main/java/org/opensearch/ad/indices/AnomalyDetectionIndices.java
Backport #1012 to 2.x. 
Previous revert change is included in this backport pr because it was manually triggered as a separate pr. 
=> [Backport to 2.10] upgrading commons-lang3 version to fix conflict issue 

.github/workflows/test_build_multi_platform.yml, .github/workflows/test_security.yml, build.gradle
Issue:
- In versions between 1.1 and 2.10, the task :adBwcCluster#twoThirdsUpgradedClusterTask fails.
- Symptoms mirror those in [OpenSearch Issue #5076](https://github.com/opensearch-project/OpenSearch/issues/5076).
- Logs show nodes from old and new versions failing to join as a cluster, resulting in a "master not found" exception.
- Similar things happened between 1.1 and 2.9/2.8 when task :adBwcCluster#mixedClusterTask executes.
Resolution:
- Upgraded the bwc version to 1.3.2, aligning with other plugins which use 1.3+ as their baseline.
- [Cross-Cluster Replication PR #469](https://github.com/opensearch-project/cross-cluster-replication/pull/469)
- [Security PR #2253](https://github.com/opensearch-project/security/pull/2253)
- [ML Commons PR …
=> Upgrade AD's bwc baseline version to 1.3.2 to resolve cluster join issue

.github/workflows/test_security.yml, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java
The security test workflow is currently skipping running tests with security quietly. See the example from the latest commit on main [here](https://github.com/opensearch-project/anomaly-detection/actions/runs/6103610427/job/16564313124) where `Run AD Test` is skipped. 
The expressions to set values in the github workflow are not getting executed as expected after the plugin was renamed to `time-series-analytics`
Specifically these lines:
```
plugin=`basename $(ls build/distributions/*.zip)`
version=`echo $plugin|awk -F- '{print $4}'| cut -d. -f 1-3`
plugin_version=`echo $plugin|awk -F- '{print $4}'| cut -d. -f 1-4`
qualifier=`echo $plugin|awk -F- '{print $5}'| cut -d. -f 1-1`
if $qualifier!=SNAPSHOT
then
docker_version=$version-$qualifier
else
docker_version=$version
fi
```
`echo …
=> Ensure integ tests run with security after plugin rename

src/test/java/org/opensearch/ad/transport/DeleteAnomalyDetectorTests.java, src/test/java/org/opensearch/ad/transport/EntityProfileTests.java, src/test/java/org/opensearch/ad/transport/GetAnomalyDetectorTests.java, src/test/java/org/opensearch/ad/transport/RCFPollingTests.java, src/test/java/org/opensearch/ad/transport/RCFResultTests.java, src/test/java/org/opensearch/ad/transport/SearchAnomalyResultActionTests.java, src/test/java/org/opensearch/ad/transport/ThresholdResultTests.java, src/test/java/test/org/opensearch/ad/util/FakeNode.java
React to changes from https://github.com/opensearch-project/OpenSearch/pull/9415. TransportService constructor changed to take in a `Tracer`. Since all instances of this are in tests, I added the `NoopTracer.INSTANCE` to all instances where a `TransportService` is instantiated.
Creating this PR because I saw the error in a Draft PR I have open: https://github.com/opensearch-project/anomaly-detection/pull/1027
---
=> React to Tracer changes in TransportService from core#9415

build.gradle, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java
Previously, the test checked if the new detector and the parsed new detector had different last update times. This was not the intended behavior. The correct check should be between the old and new detector's last update time. This discrepancy was mostly masked by serialization and deserialization differences, but surfaced in JDK 8 on Windows where the timestamps matched.
Changes:
- Updated test to compare old vs. new detector's last update time.
Testing:
- Ran `gradle build`.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-ce …
=> Fix AnomalyDetectorRestApiIT.testUpdateAnomalyDetectorNameToNew

build.gradle, release-notes/opensearch-anomaly-detection.release-notes-2.11.0.0.md, src/test/java/org/opensearch/ad/task/ADTaskManagerTests.java, src/test/java/org/opensearch/ad/transport/DeleteAnomalyDetectorTests.java, src/test/java/org/opensearch/ad/transport/EntityProfileTests.java, src/test/java/org/opensearch/ad/transport/GetAnomalyDetectorTests.java, src/test/java/org/opensearch/ad/transport/RCFPollingTests.java, src/test/java/org/opensearch/ad/transport/RCFResultTests.java, src/test/java/org/opensearch/ad/transport/SearchAnomalyResultActionTests.java, src/test/java/org/opensearch/ad/transport/ThresholdResultTests.java, src/test/java/test/org/opensearch/ad/util/FakeNode.java
Add a tracer field for the TransportService constructor in our test cases
Core change to add tracer in MockNioTransport https://github.com/opensearch-project/OpenSearch/pull/10143/files#diff-f37f7447c76ba79901c3298a1addce39d103ce72efc5a75a1f7602a4e2829b62R115
core changes to add tracker in TransportService https://github.com/opensearch-project/OpenSearch/commit/27cddec134844a8061b9a7f9cc5eee2e4622feec
=> [2.x] Fix TransportService constructor due to changes in core plus guava bump

.github/workflows/benchmark.yml, .github/workflows/test_build_multi_platform.yml, .github/workflows/test_bwc.yml, .github/workflows/test_security.yml
Backport 2.x #1092 #1093
#1073 
=> Backport 2.x #1092 #1093

build.gradle, dataGeneration/requirements.txt, src/test/java/test/org/opensearch/ad/util/FakeNode.java
Adds a `Tracer` parameter to fix the build (failed testCompile).
Updates jupiter engine version to match dependencies.
Updates versions of dependencies impacted by CVEs.
- the eclipse runtime version bump now requires JDK17+ to run spotless
=> Fix build, update CVE-affected versions

src/main/java/org/opensearch/ad/client/AnomalyDetectionClient.java, src/main/java/org/opensearch/ad/client/AnomalyDetectionNodeClient.java, src/test/java/org/opensearch/ad/client/AnomalyDetectionClientTests.java, src/test/java/org/opensearch/ad/client/AnomalyDetectionNodeClientTests.java
=> [2.x] Add an AD transport client

src/main/java/org/opensearch/ad/client/AnomalyDetectionClient.java, src/main/java/org/opensearch/ad/client/AnomalyDetectionNodeClient.java, src/main/java/org/opensearch/ad/transport/ADTaskProfileResponse.java, src/test/java/org/opensearch/ad/client/AnomalyDetectionClientTests.java, src/test/java/org/opensearch/ad/client/AnomalyDetectionNodeClientTests.java, src/test/java/org/opensearch/ad/transport/ADTaskProfileResponseTests.java
Adds a profile transport action method to the AD client. Note this method only takes in a `detectorId` string vs. the full `ADTaskProfileRequest` as required by the transport action. This is to simplify the interface and requirements from caller's side, as generating the request is not trivial and requires some AD-specific logic, including the constructed `DiscoveryNodeFilterer` used to determine the eligible AD nodes for the transport action to distribute the `ADTaskProfileRequest` to.
Additionally, this updates the `ADTaskProfileResponse` to add a helper method to serialize from a generic `ActionResponse`. This is needed to prevent classloader issues and ClassCastExceptions when this is constructed from external plugins using the AD client. 
Adds relevant tests and some minor cleanup on …
=> Add profile transport action to AD client

src/main/java/org/opensearch/ad/client/AnomalyDetectionClient.java, src/main/java/org/opensearch/ad/client/AnomalyDetectionNodeClient.java, src/main/java/org/opensearch/ad/transport/ADTaskProfileResponse.java, src/test/java/org/opensearch/ad/client/AnomalyDetectionClientTests.java, src/test/java/org/opensearch/ad/client/AnomalyDetectionNodeClientTests.java, src/test/java/org/opensearch/ad/transport/ADTaskProfileResponseTests.java
Backport #1119 to `2.x`.
Manual backport needed to resolve merge conflicts for import statements due to refactoring on 3.x.
=> [Backport 2.x] Add profile transport action to AD client

src/main/java/org/opensearch/ad/client/AnomalyDetectionClient.java, src/main/java/org/opensearch/ad/client/AnomalyDetectionNodeClient.java, src/main/java/org/opensearch/ad/transport/GetAnomalyDetectorResponse.java, src/test/java/org/opensearch/ad/client/AnomalyDetectionClientTests.java, src/test/java/org/opensearch/ad/client/AnomalyDetectionNodeClientTests.java
The previous implementation of `getDetectorProfile()` used the `ADTaskProfileAction` which had the following limitations:
- very specific to tasks and may not contain other general AD-related things, such as detector name, AD-job status, etc.
- required `ClusterService` to be passed in the client construction which added effort from the caller's end
- the response was inherently more complex, and contained a list of individual node responses from each node in the cluster
- difficulty in interfacing historical vs. realtime tasks and propagating those results
This changes that to use the `GetAnomalyDetectorTransportAction`, which is a more high-level transport action that more closely emulates that of the [profile API](https://opensearch.org/docs/latest/observing-your-data/ad/api/#profile-de …
=> Refactor client's getDetectorProfile to use GetAnomalyDetectorTransportAction

src/main/java/org/opensearch/ad/client/AnomalyDetectionClient.java, src/main/java/org/opensearch/ad/client/AnomalyDetectionNodeClient.java, src/main/java/org/opensearch/ad/transport/GetAnomalyDetectorResponse.java, src/test/java/org/opensearch/ad/client/AnomalyDetectionClientTests.java, src/test/java/org/opensearch/ad/client/AnomalyDetectionNodeClientTests.java
Manual backport of #1124. Needed due to import refactoring done on 3.x.
=> [Backport 2.x] Refactor client's getDetectorProfile to use GetAnomalyDetectorTransportAction (#1124)

scripts/build.sh
add publishToMavenLocal task to fix zip plugin not published to maven local issue when running this script
add publishToMavenLocal task to fix zip plugin not published to maven local issue when running this script
=> add publishToMavenLocal task to fix zip plugin not published to maven local issue when running this script

src/main/java/org/opensearch/ad/transport/GetAnomalyDetectorRequest.java, src/main/java/org/opensearch/ad/transport/GetAnomalyDetectorTransportAction.java
Previously there was no serialization and deserialization of the `GetAnomalyDetectorRequest` passed to the transport action. Because this transport action is exposed via the AD node client, it is possible a user executes this from a different classloader of AD classes, such that there is ClassCastExceptions when propagating the `GetAnomalyDetectorRequest`. Similar to other existing req/resp objects, this PR adds a `fromActionRequest` method to serialize & deserialize a base `ActionRequest` into a `GetAnomalyDetectorRequest` when running `execute()` to prevent such errors.
I've confirmed this works by triggering the error, and seeing the fix, by executing this using the [skills repo](https://github.com/opensearch-project/skills)'s `SearchAnomalyDetectorsTool`. This tool, for a certain …
=> Improve GetAnomalyDetectorTransportAction to accept generic ActionRequest

src/main/java/org/opensearch/ad/transport/GetAnomalyDetectorRequest.java, src/main/java/org/opensearch/ad/transport/GetAnomalyDetectorTransportAction.java
Manual backport of #1150 due to conflict with imports. No logic changes.
=> [Backport 2.x] Improve GetAnomalyDetectorTransportAction to accept generic ActionRequest (#1150)

src/main/java/org/opensearch/ad/client/AnomalyDetectionNodeClient.java, src/main/java/org/opensearch/ad/transport/GetAnomalyDetectorResponse.java, src/test/java/org/opensearch/ad/client/AnomalyDetectionNodeClientTests.java, src/test/java/org/opensearch/ad/transport/GetAnomalyDetectorResponseTests.java
Currently, when serializing the `GetAnomalyDetectorResponse` via `fromActionResponse` (triggered by executing via the node client from a separate plugin) it is not passing a named-writeable-aware stream input, which causes serialization to fail for certain sub-fields within `GetAnomalyDetectorResponse` that are trying to read named writeables via `readNamedWriteable()`. Error seen:
```
Caused by: java.lang.UnsupportedOperationException: can't read named writeable from StreamInput
```
This fixes that by changing the constructor of the node client to pass in a `NamedWriteableRegistry`, to finally pass down to `fromActionResponse` to construct a valid `NamedWriteableAwareStreamInput` to successfully serialize and return a `GetAnomalyDetectorResponse`.
Note `fromActionResponse()` is only used …
=> Inject NamedWriteableRegistry in AD node client

src/main/java/org/opensearch/ad/caching/PriorityCache.java, src/main/java/org/opensearch/ad/task/ADTaskCacheManager.java, src/main/java/org/opensearch/timeseries/MemoryTracker.java, src/main/java/org/opensearch/timeseries/settings/TimeSeriesSettings.java, src/test/java/org/opensearch/action/admin/indices/mapping/get/IndexAnomalyDetectorActionHandlerTests.java, src/test/java/org/opensearch/ad/TRCFMemoryTests.java, src/test/java/org/opensearch/ad/caching/PriorityCacheTests.java, src/test/java/org/opensearch/forecast/CasterMemoryTests.java, src/test/java/org/opensearch/timeseries/AbstractMemoryTrackerTest.java
This PR accomplishes two main objectives:
* Tree Count Enhancement: Increases the number of trees to 50, aiming to improve RCF models' accuracy and robustness.
* Memory Calculation Update: Adjusts the memory calculation formula due to upgrades in the RCF library and changes in parameters.
Methodology for Memory Calculation:
The updated memory calculation follows the methodology in [PR #222](https://github.com/opensearch-project/anomaly-detection/pull/222). It involves running TRCF or RCFCaster with one million data points and measuring object sizes using jmap memory dumps. This white-box approach examines all fields listed under the heap dump to account for various scenarios, such as fluctuations in node store size due to parameter changes. Additionally, the point store ratio adjustment …
=> Increase Tree Count to 50 & Update Memory Calculation for RCF models

.github/workflows/test_build_multi_platform.yml, build.gradle, src/test/java/org/opensearch/ad/transport/AnomalyDetectorJobTransportActionTests.java
This PR also backported partial changes from https://github.com/opensearch-project/anomaly-detection/pull/1173 to fix failed CI.
* fixed the issue related to https://github.com/opensearch-project/flow-framework/pull/175/files
* fixed flaky test AnomalyDetectorJobTransportActionTests.testStartHistoricalAnalysisForSingleCategoryHCWithUser by changing waiting condition and increase timeout value.
=>  Increment version to 2.14.0

src/main/java/org/opensearch/ad/model/ADTask.java, src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/main/java/org/opensearch/ad/rest/handler/AbstractAnomalyDetectorActionHandler.java, src/main/java/org/opensearch/forecast/model/ForecastTask.java, src/main/java/org/opensearch/forecast/model/Forecaster.java, src/main/java/org/opensearch/forecast/rest/handler/AbstractForecasterActionHandler.java, src/main/java/org/opensearch/timeseries/model/Config.java, src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/model/AnomalyDetectorTests.java, src/test/java/org/opensearch/ad/rest/ADRestTestUtils.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/rest/HistoricalAnalysisRestApiIT.java, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java, src/test/java/org/opensearch/ad/transport/AnomalyResultTransportActionTests.java, src/test/java/org/opensearch/ad/transport/ForwardADTaskRequestTests.java, src/test/java/org/opensearch/ad/transport/ValidateAnomalyDetectorTransportActionTests.java, src/test/java/org/opensearch/forecast/model/ForecasterTests.java, src/test/java/org/opensearch/timeseries/TestHelpers.java
Add custom result index lifecycle management condition fields to config
https://github.com/opensearch-project/anomaly-detection/issues/1213
=> Add custom result index lifecycle management condition fields to config

src/main/java/org/opensearch/ad/indices/ADIndexManagement.java
ADIndexManagement inherits from IndexManagement, which implements LocalNodeClusterManagerListener, causing it to listen for master node changes. This listener schedules index rollover and deletion. However, ADIndexManagement was inadvertently listening to the cluster manager event again, leading to duplicate scheduling of these tasks.
This commit removes the redundant listener call in ADIndexManagement, ensuring that index rollover and deletion are scheduled only once per interval.
Testing:
* Verified that index rollover and deletion now execute once per interval as expected.
For more information on following Developer Certificate of Origin and signing off your commits, …
=> Fix Duplicate Scheduling of Index Rollover in ADIndexManagement

src/main/java/org/opensearch/timeseries/indices/IndexManagement.java
This PR addresses two issues to enhance robustness in the IndexManagement class:
* Null Check for Candidate Result Aliases:
* Added a null check for candidateResultAliases in updateCustomResultIndexMapping to prevent NullPointerExceptions.
* Graceful Handling for Missing Config Index:
* Modified searchConfigs to return an empty list instead of throwing a ResourceNotFoundException when the config index does not exist.
Testing:
* Verified that NullPointerExceptions are prevented and the system gracefully handles cases where the config index does not exist. …
=> Fix Null Pointer Exception and Improve Handling for Missing Config Index

src/main/java/org/opensearch/ad/indices/ADIndexManagement.java, src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/main/java/org/opensearch/forecast/indices/ForecastIndexManagement.java, src/main/java/org/opensearch/timeseries/indices/IndexManagement.java, src/test/java/org/opensearch/ad/indices/RolloverTests.java
Add custom result index lifecycle management. AD doesn't provide customer the ability to manage their custom result index lifecycle before, customers can only go to ISM to manage it. Now we allow customer to add index lifecycle management conditions at frontend, and we manage them inside AD
https://github.com/opensearch-project/anomaly-detection/issues/1213
=> add custom result index lifecycle management

src/main/java/org/opensearch/ad/AnomalyDetectorProfileRunner.java, src/main/java/org/opensearch/ad/ml/ADCheckpointDao.java, src/main/java/org/opensearch/timeseries/transport/BaseProfileTransportAction.java, src/test/java/org/opensearch/ad/AbstractProfileRunnerTests.java, src/test/java/org/opensearch/ad/AnomalyDetectorProfileRunnerTests.java, src/test/java/org/opensearch/ad/OldAnomalyDetectorProfileRunner.java, src/test/java/org/opensearch/search/aggregations/metrics/CardinalityProfileTests.java
Since version 2.15, we have merged the single-stream and HC detector workflows. Consequently, separate logic for profiling is no longer necessary. This PR removes single-stream specific logic from the profile runner.
During a Blue/Green (B/G) deployment, if an old node communicates with a new node regarding an old model, we will not execute RCFPollingAction to determine model updates. However, we have fallback logic that checks for anomaly results. If any results are found, the initialization progress is set to 100%.
I have retained the old AnomalyDetectorProfileRunner temporarily to facilitate writing tests for the legacy logic. This includes keeping RCFPollingAction and ModelManager.getTotalUpdates to handle requests from old nodes during the B/G deployment process.
Testing:
* Verified …
=> Merge Single-Stream and HC Detector Profiling Workflows

src/main/java/org/opensearch/ad/AnomalyDetectorProfileRunner.java, src/main/java/org/opensearch/ad/ml/ADCheckpointDao.java, src/main/java/org/opensearch/timeseries/transport/BaseProfileTransportAction.java, src/test/java/org/opensearch/ad/AbstractProfileRunnerTests.java, src/test/java/org/opensearch/ad/AnomalyDetectorProfileRunnerTests.java, src/test/java/org/opensearch/ad/OldAnomalyDetectorProfileRunner.java, src/test/java/org/opensearch/search/aggregations/metrics/CardinalityProfileTests.java
backport https://github.com/opensearch-project/anomaly-detection/pull/1237 to 2.15
=> [backport to 2.15] Merge Single-Stream and HC Detector Workflows (#1237) (#1239)

src/main/java/org/opensearch/timeseries/constant/CommonName.java, src/main/java/org/opensearch/timeseries/rest/handler/AbstractTimeSeriesActionHandler.java, src/test/java/org/opensearch/ad/ADIntegTestCase.java, src/test/java/org/opensearch/ad/e2e/RuleModelPerfIT.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/transport/ValidateAnomalyDetectorTransportActionTests.java, src/test/java/org/opensearch/timeseries/TestHelpers.java
This PR add support for **date_nanos** type for time field in Anomaly Detection. 
[#1226](https://github.com/opensearch-project/anomaly-detection/issues/1226)
=> feat: Adding support for date_nanos to Anomaly Detection

.github/workflows/maven-publish.yml, .github/workflows/test_build_multi_platform.yml, .github/workflows/test_bwc.yml, .github/workflows/test_security.yml, build.gradle
Sets the baseline JDK version to JDK-21
Resolves #1223
=> Set baseline JDK version to JDK-21

build.gradle, src/main/java/org/opensearch/timeseries/TimeSeriesAnalyticsPlugin.java, src/main/java/org/opensearch/timeseries/constant/CommonName.java
This PR registers the system indices in this plugin through the SystemIndexPlugin extension point in core. These indices will not be functionally different than they are today, its just a formal registration as a system index.
Related to https://github.com/opensearch-project/security/issues/4439
=> Register system index descriptors through SystemIndexPlugin.getSystemIndexDescriptors

src/main/java/org/opensearch/ad/model/ADTask.java, src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/main/java/org/opensearch/ad/rest/handler/AbstractAnomalyDetectorActionHandler.java, src/main/java/org/opensearch/forecast/model/ForecastTask.java, src/main/java/org/opensearch/forecast/model/Forecaster.java, src/main/java/org/opensearch/forecast/rest/handler/AbstractForecasterActionHandler.java, src/main/java/org/opensearch/timeseries/model/Config.java, src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/model/AnomalyDetectorTests.java, src/test/java/org/opensearch/ad/rest/ADRestTestUtils.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/rest/HistoricalAnalysisRestApiIT.java, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java, src/test/java/org/opensearch/ad/transport/AnomalyResultTransportActionTests.java, src/test/java/org/opensearch/ad/transport/ForwardADTaskRequestTests.java, src/test/java/org/opensearch/ad/transport/ValidateAnomalyDetectorTransportActionTests.java, src/test/java/org/opensearch/forecast/model/ForecasterTests.java, src/test/java/org/opensearch/timeseries/TestHelpers.java
Add flatten_result_index_mapping field to Config
https://github.com/opensearch-project/anomaly-detection/issues/1213
=> Add flatten_result_index_mapping field to Config

.github/workflows/long_running.yml, build.gradle, src/main/java/org/opensearch/timeseries/dataprocessor/ImputationOption.java, src/main/java/org/opensearch/timeseries/ml/ModelManager.java, src/main/java/org/opensearch/timeseries/ml/ModelState.java, src/main/java/org/opensearch/timeseries/ml/RealTimeInferencer.java, src/main/java/org/opensearch/timeseries/model/Config.java, src/main/resources/mappings/config.json, src/test/java/org/opensearch/ad/AbstractADSyntheticDataTest.java, src/test/java/org/opensearch/ad/e2e/AbstractMissingSingleFeatureTestCase.java, src/test/java/org/opensearch/ad/e2e/HistoricalRuleModelPerfIT.java, src/test/java/org/opensearch/ad/e2e/MissingMultiFeatureIT.java, src/test/java/org/opensearch/ad/e2e/SingleStreamModelPerfIT.java, src/test/java/org/opensearch/ad/e2e/SingleStreamSmokeIT.java, src/test/java/org/opensearch/ad/indices/RolloverTests.java, src/test/java/org/opensearch/ad/model/AnomalyDetectorTests.java, src/test/java/org/opensearch/timeseries/dataprocessor/ImputationOptionTests.java
This commit addresses several issues and improvements in the inference logic and config index mapping:
1. Fixes in RealTimeInferencer:
* Previously, we checked if the last update time of the model state was within the current interval and skipped inference if it was. However, this led to excessive skipping of inference because the last update time was updated when retrieving the model state from the cache.
* Introduced lastSeenExecutionEndTime in the model state, which specifically tracks the last time a sample was processed during inference (not training). This ensures more accurate control over when inference should be skipped.
2. Consistent Naming in Config Index Mapping:
* To maintain consistency across the codebase, changed defaultFill to default_fill in the Config index mapping, …
=> Fix inference logic and standardize config index mapping

build.gradle, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/ad/transport/ADHCImputeTransportAction.java, src/main/java/org/opensearch/forecast/task/ForecastTaskManager.java, src/main/java/org/opensearch/timeseries/ml/RealTimeInferencer.java, src/main/java/org/opensearch/timeseries/model/Config.java, src/main/java/org/opensearch/timeseries/task/TaskManager.java, src/test/java/org/opensearch/ad/AbstractADSyntheticDataTest.java, src/test/java/org/opensearch/ad/e2e/AbstractRuleTestCase.java, src/test/java/org/opensearch/ad/e2e/MissingIT.java, src/test/java/org/opensearch/ad/e2e/MixedRealtimeHistoricalIT.java, src/test/java/org/opensearch/ad/model/AnomalyDetectorTests.java, src/test/java/org/opensearch/timeseries/TestHelpers.java
This PR addresses a bug where starting a historical analysis after a real-time analysis on the same detector caused the real-time task’s latest flag to be incorrectly reset to false by the historical run.
The fix ensures that only the latest flags of the same analysis type are reset:
* Real-time analysis will only reset the latest flag of previous real-time analyses.
* Historical analysis will only reset the latest flag of previous historical analyses.
Additional Changes:
* Set a minimum recencyEmphasis value of 2 to align with RCF requirements.
* Updated imputation logic to execute only when the entity maps to the local node ID in the hash ring, reducing errors when models of the same entity exist on multiple nodes.
Testing:
- Added an integration test to reproduce the bug and verified …
=> Prevent resetting latest flag of real-time when starting historical analysis

src/main/java/org/opensearch/timeseries/util/ParseUtils.java, src/test/java/org/opensearch/timeseries/util/ParseUtilsTests.java
Previously, when the max aggregation in SearchResponse returned a null value, it was converted to a negative number (-9223372036854775808), leading to erroneous timestamps.
This fix adds a check to ensure that only valid positive aggregation values are considered, preventing null or invalid values from being misinterpreted as negative numbers. The change applies to only timestamps. So a positive number filter is always right.
Testing done:
1. Added unit tests to cover scenarios where max aggregation returns null or negative values, ensuring the method returns Optional.empty() when the value is invalid.
2. Added unit tests to verify correct handling of valid positive max aggregation values.
3. Ran e2e manual testing.
Previously:
```
POST …
```
=> Correct handling of null max aggregation values in SearchResponse

src/main/java/org/opensearch/timeseries/constant/CommonMessages.java, src/main/java/org/opensearch/timeseries/rest/RestValidateAction.java, src/main/java/org/opensearch/timeseries/rest/handler/AbstractTimeSeriesActionHandler.java, src/main/java/org/opensearch/timeseries/transport/BaseValidateConfigTransportAction.java, src/main/java/org/opensearch/timeseries/util/CrossClusterConfigUtils.java, src/main/java/org/opensearch/timeseries/util/MultiResponsesDelegateActionListener.java, src/test/java/org/opensearch/action/admin/indices/mapping/get/AbstractForecasterActionHandlerTestCase.java, src/test/java/org/opensearch/action/admin/indices/mapping/get/IndexAnomalyDetectorActionHandlerTests.java, src/test/java/org/opensearch/action/admin/indices/mapping/get/IndexForecasterActionHandlerTests.java, src/test/java/org/opensearch/action/admin/indices/mapping/get/ValidateAnomalyDetectorActionHandlerTests.java, src/test/java/org/opensearch/action/admin/indices/mapping/get/ValidateForecasterActionHandlerTests.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/transport/ValidateAnomalyDetectorTransportActionTests.java, src/test/java/org/opensearch/timeseries/util/CrossClusterConfigUtilsTests.java
Adds ability to validate multiple indices/aliases and remote indices during validation, rest of the remote indexing feature actually works out of the box on any search action that is done. 
1. Validation for timefield works based on the fact that all indices given should have the given timestamp or we fail
2. Validation for categorical field is similar that we required all indices to have the given categorical field
Tasks left over:
- Writing a few more integ tests and fixing one more broken unit tests
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/anomaly-detection/blob/ …
=> Adding remote index and multi-index checks in validation

src/main/java/org/opensearch/timeseries/feature/SearchFeatureDao.java, src/main/java/org/opensearch/timeseries/rest/handler/AbstractTimeSeriesActionHandler.java, src/main/java/org/opensearch/timeseries/rest/handler/IntervalCalculation.java, src/main/java/org/opensearch/timeseries/rest/handler/LatestTimeRetriever.java, src/main/java/org/opensearch/timeseries/rest/handler/ModelValidationActionHandler.java, src/main/java/org/opensearch/timeseries/util/CrossClusterConfigUtils.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/forecast/rest/ForecastRestApiIT.java
Changed getLatestDataTime so we pass the correct user so we have the right user info when querying remote indices, otherwise we get a failure like: 
```
nested: RemoteTransportException[[35692e6c255f][172.22.0.4:9300][indices:data/read/search]]; nested: OpenSearchSecurityException[No user found for indices:data/read/search];
```
=> Passing user to getLatestDataTime call

src/test/java/org/opensearch/ad/rest/SecureADRestIT.java
This PR addresses errors in security tests caused by recent changes in opensearch-project/security#4719. Previously, users needed both AD full access and source index permissions to fully utilize anomaly detection (AD). AD full access has already included all alias and mapping permissions.  it was inconsistent not to include index search permission, which would otherwise force users to create an additional role. The change in the referenced PR aimed to simplify user management.
Due to this change, existing security tests that relied on a user having AD full access but lacking data search permission would no longer trigger the expected search permission exception. This PR addresses that issue by creating a new user role with only AD read permission (note we didn't change ad read access …
=> Fix Security Tests After Changes to Permissions Requirements

build.gradle, src/main/java/org/opensearch/ad/model/AnomalyResult.java, src/main/java/org/opensearch/ad/transport/GetAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/forecast/model/ForecastResult.java, src/main/java/org/opensearch/timeseries/caching/PriorityCache.java, src/main/java/org/opensearch/timeseries/transport/BaseGetConfigTransportAction.java, src/main/java/org/opensearch/timeseries/transport/ResultProcessor.java, src/test/java/org/opensearch/ad/HistoricalAnalysisRestTestCase.java, src/test/java/org/opensearch/ad/caching/PriorityCacheTests.java, src/test/java/org/opensearch/ad/e2e/AbstractRuleTestCase.java, src/test/java/org/opensearch/ad/e2e/PreviewRuleIT.java, src/test/java/org/opensearch/ad/e2e/RealTimeRuleIT.java, src/test/java/org/opensearch/ad/ml/EntityColdStarterTests.java, src/test/java/org/opensearch/ad/model/AnomalyResultTests.java, src/test/java/org/opensearch/ad/model/GetAnomalyDetectorTransportActionTests.java, src/test/java/org/opensearch/ad/rest/HistoricalAnalysisRestApiIT.java, src/test/java/org/opensearch/ad/transport/ADHCImputeNodesResponseTests.java, src/test/java/org/opensearch/forecast/transport/GetForecasterTransportActionTests.java
This PR includes the following updates and bug fixes:
* Bump BWC Version to 2.18: Updated BWC version to 2.18 since the 2.17 branch has been cut.
* Fix Confidence Value Exceeding 1 in RCF: Addressed a bug in RCF where the confidence value could exceed 1. Implemented a check to cap the confidence value at 1, preventing invalid confidence scores.
* Correct Parameter Assignment in GetAnomalyDetectorTransportAction: Fixed an issue where parameter assignments within a method did not affect external variables due to Java's pass-by-value nature.
* Fixed a bug in ResultProcessor where we were supposed to check whether the number of sent messages equals the number of received messages before starting imputation. However, the sent message count was mistakenly based on the number of pages rather …
=> Bump BWC Version to 2.18 and Fix Bugs

build.gradle, src/main/java/org/opensearch/ad/model/AnomalyResult.java, src/main/java/org/opensearch/ad/transport/GetAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/forecast/model/ForecastResult.java, src/main/java/org/opensearch/timeseries/caching/PriorityCache.java, src/main/java/org/opensearch/timeseries/transport/BaseGetConfigTransportAction.java, src/main/java/org/opensearch/timeseries/transport/ResultProcessor.java, src/test/java/org/opensearch/ad/HistoricalAnalysisRestTestCase.java, src/test/java/org/opensearch/ad/caching/PriorityCacheTests.java, src/test/java/org/opensearch/ad/e2e/AbstractRuleTestCase.java, src/test/java/org/opensearch/ad/e2e/PreviewRuleIT.java, src/test/java/org/opensearch/ad/e2e/RealTimeRuleIT.java, src/test/java/org/opensearch/ad/ml/EntityColdStarterTests.java, src/test/java/org/opensearch/ad/model/AnomalyResultTests.java, src/test/java/org/opensearch/ad/model/GetAnomalyDetectorTransportActionTests.java, src/test/java/org/opensearch/ad/rest/HistoricalAnalysisRestApiIT.java, src/test/java/org/opensearch/ad/transport/ADHCImputeNodesResponseTests.java, src/test/java/org/opensearch/forecast/transport/GetForecasterTransportActionTests.java
backport https://github.com/opensearch-project/anomaly-detection/pull/1311 to 2.17
=> [backport to 2.17] Bump BWC Version to 2.18 and Fix Bugs (#1311)

build.gradle, src/main/java/org/opensearch/ad/model/AnomalyResult.java, src/main/java/org/opensearch/ad/transport/GetAnomalyDetectorTransportAction.java, src/main/java/org/opensearch/forecast/model/ForecastResult.java, src/main/java/org/opensearch/timeseries/caching/PriorityCache.java, src/main/java/org/opensearch/timeseries/transport/BaseGetConfigTransportAction.java, src/main/java/org/opensearch/timeseries/transport/ResultProcessor.java, src/test/java/org/opensearch/ad/HistoricalAnalysisRestTestCase.java, src/test/java/org/opensearch/ad/caching/PriorityCacheTests.java, src/test/java/org/opensearch/ad/e2e/AbstractRuleTestCase.java, src/test/java/org/opensearch/ad/e2e/PreviewRuleIT.java, src/test/java/org/opensearch/ad/e2e/RealTimeRuleIT.java, src/test/java/org/opensearch/ad/ml/EntityColdStarterTests.java, src/test/java/org/opensearch/ad/model/AnomalyResultTests.java, src/test/java/org/opensearch/ad/model/GetAnomalyDetectorTransportActionTests.java, src/test/java/org/opensearch/ad/rest/HistoricalAnalysisRestApiIT.java, src/test/java/org/opensearch/ad/transport/ADHCImputeNodesResponseTests.java, src/test/java/org/opensearch/forecast/transport/GetForecasterTransportActionTests.java
backport https://github.com/opensearch-project/anomaly-detection/pull/1311 to 2.x
=> [backport to 2.x] Bump BWC Version to 2.18 and Fix Bugs (#1311)

build.gradle, src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/main/java/org/opensearch/timeseries/JobProcessor.java, src/main/java/org/opensearch/timeseries/ratelimit/ColdStartWorker.java, src/main/java/org/opensearch/timeseries/rest/handler/IndexJobActionHandler.java, src/main/java/org/opensearch/timeseries/transport/handler/ResultBulkIndexingHandler.java, src/test/java/org/opensearch/ad/e2e/AbstractRuleTestCase.java, src/test/java/org/opensearch/ad/ml/ADColdStartTests.java, src/test/java/org/opensearch/ad/task/ADTaskManagerTests.java, src/test/java/org/opensearch/ad/transport/handler/AnomalyResultBulkIndexHandlerTests.java, src/test/java/org/opensearch/timeseries/TestHelpers.java, src/test/java/org/opensearch/timeseries/transport/JobRequestTests.java
* Updated RCF version to the latest release.
* Fixed a bug in AnomalyDetector where default rules were not applied when the user provided an empty ruleset.
Testing:
* Added unit tests to cover the bug fix
=> Bump RCF Version and Fix Default Rules Bug in AnomalyDetector

build.gradle, src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/main/java/org/opensearch/timeseries/JobProcessor.java, src/main/java/org/opensearch/timeseries/ratelimit/ColdStartWorker.java, src/main/java/org/opensearch/timeseries/rest/handler/IndexJobActionHandler.java, src/main/java/org/opensearch/timeseries/transport/handler/ResultBulkIndexingHandler.java, src/test/java/org/opensearch/ad/e2e/AbstractRuleTestCase.java, src/test/java/org/opensearch/ad/e2e/HistoricalRuleModelPerfIT.java, src/test/java/org/opensearch/ad/e2e/RealTimeRuleModelPerfIT.java, src/test/java/org/opensearch/ad/ml/ADColdStartTests.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/task/ADTaskManagerTests.java, src/test/java/org/opensearch/ad/transport/handler/AnomalyResultBulkIndexHandlerTests.java, src/test/java/org/opensearch/timeseries/TestHelpers.java, src/test/java/org/opensearch/timeseries/transport/JobRequestTests.java
Backport 2ab6dc7f034947ef10a3ca0c422ca41a646c511b from #1334.
=> [backport to 2.x] Bump RCF Version and Fix Default Rules Bug in AnomalyDetector

.github/workflows/draft-release-notes-workflow.yml, .github/workflows/test_build_multi_platform.yml, build.gradle
Updating several dependencies in one PR so its easier to rebase vs a few of the outdated dependabot PRs we have. 
I also removed `javassist` as we don't seem to use it, locally all tests passed without it.
=> Updating several dependencies

build.gradle, src/main/java/org/opensearch/ad/ml/ADModelManager.java, src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/main/java/org/opensearch/timeseries/ml/MemoryAwareConcurrentHashmap.java, src/main/java/org/opensearch/timeseries/model/ValidationIssueType.java, src/main/java/org/opensearch/timeseries/transport/SuggestConfigParamRequest.java, src/test/java/org/opensearch/ad/e2e/HistoricalRuleModelPerfIT.java, src/test/java/org/opensearch/ad/e2e/RealTimeRuleModelPerfIT.java, src/test/java/org/opensearch/ad/model/AnomalyDetectorTests.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/timeseries/transport/SuggestConfigParamRequestTests.java, src/test/java/org/opensearch/timeseries/transport/SuggestConfigParamResponseTests.java
This commit introduces rule validation within the AnomalyDetector constructor. Any validation errors are now propagated and displayed on the frontend to ensure immediate feedback.
Testing:
* Verified that validation errors are properly propagated and shown on the frontend.
* Added UTs to cover the new validation logic.
=> Add rule validation in AnomalyDetector constructor

src/main/java/org/opensearch/ad/model/ADTask.java, src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/main/java/org/opensearch/ad/rest/handler/AbstractAnomalyDetectorActionHandler.java, src/main/java/org/opensearch/forecast/model/ForecastTask.java, src/main/java/org/opensearch/forecast/model/Forecaster.java, src/main/java/org/opensearch/forecast/rest/handler/AbstractForecasterActionHandler.java, src/main/java/org/opensearch/timeseries/model/Config.java, src/test/java/org/opensearch/action/admin/indices/mapping/get/IndexAnomalyDetectorActionHandlerTests.java, src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/model/AnomalyDetectorTests.java, src/test/java/org/opensearch/ad/rest/ADRestTestUtils.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/rest/HistoricalAnalysisRestApiIT.java, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java, src/test/java/org/opensearch/ad/transport/AnomalyResultTransportActionTests.java, src/test/java/org/opensearch/ad/transport/ForwardADTaskRequestTests.java, src/test/java/org/opensearch/ad/transport/ValidateAnomalyDetectorTransportActionTests.java, src/test/java/org/opensearch/forecast/model/ForecasterTests.java, src/test/java/org/opensearch/timeseries/TestHelpers.java
This reverts commit cbe1f336faf237907e4786d4c7db429a9126954c.
=> Revert "Add flatten_result_index_mapping field to Config (#1317)"

src/main/java/org/opensearch/timeseries/transport/ResultBulkTransportAction.java, src/main/java/org/opensearch/timeseries/transport/ResultProcessor.java, src/test/java/org/opensearch/ad/e2e/AbstractMissingSingleFeatureTestCase.java, src/test/java/org/opensearch/ad/e2e/MissingIT.java, src/test/java/org/opensearch/ad/e2e/MissingMultiFeatureIT.java, src/test/java/org/opensearch/ad/e2e/PreviewMissingSingleFeatureIT.java
This PR
- Introduced an `AtomicInteger` called `pagesInFlight` to track the number of pages currently being processed. 
- Incremented `pagesInFlight` before processing each page and decremented it after processing is complete
- Adjusted the condition in `scheduleImputeHCTask` to check both `pagesInFlight.get() == 0` (all pages have been processed) and `sentOutPages.get() == receivedPages.get()` (all responses have been received) before scheduling the `imputeHC` task. 
- Removed the previous final check in `onResponse` that decided when to schedule `imputeHC`, relying instead on the updated counters for accurate synchronization.
These changes address the race condition where `sentOutPages` might not have been incremented in time before checking whether to schedule the `imputeHC` task. By …
=> Fix race condition in PageListener

src/main/java/org/opensearch/timeseries/indices/IndexManagement.java
Changing auto expand replica setting for custom result index to 0-2 so we have at least 2 replicas when node count is over 2.
=> Changing replica count to up 2 for custom result index

.github/workflows/benchmark.yml, .github/workflows/link-check-workflow.yml, .github/workflows/long_running.yml, .github/workflows/maven-publish.yml, .github/workflows/test_build_multi_platform.yml, .github/workflows/test_bwc.yml, build.gradle
Updating several different dependencies that we have outdated depandabot PRs for.
Also testing out this [solution](https://github.com/opensearch-project/opensearch-build/issues/5178) for some of our workflows that still have checkout@v3. 
=> Updating setup-java, byte buddy, jacoco and mockito dependencies 

src/main/java/org/opensearch/ad/ml/IgnoreSimilarExtractor.java, src/main/java/org/opensearch/ad/ml/ThresholdingResult.java, src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/main/java/org/opensearch/ad/model/AnomalyResult.java, src/main/java/org/opensearch/ad/model/Condition.java, src/main/java/org/opensearch/ad/model/ThresholdType.java, src/main/java/org/opensearch/ad/transport/AnomalyResultResponse.java, src/main/java/org/opensearch/forecast/transport/ForecastResultResponse.java, src/main/java/org/opensearch/timeseries/ExecuteResultResponseRecorder.java, src/main/java/org/opensearch/timeseries/model/Feature.java, src/main/java/org/opensearch/timeseries/model/FeatureData.java, src/main/java/org/opensearch/timeseries/rest/handler/IndexJobActionHandler.java, src/main/java/org/opensearch/timeseries/transport/ResultResponse.java, src/test/java/org/opensearch/ad/model/AnomalyDetectorTests.java, src/test/java/org/opensearch/ad/model/AnomalyResultTests.java
This PR expands on the custom supression rules that we have added in 2.17. Users now have the ability to configures rules which have x number of conditions in them regarding the feature. 
Rules can look like this:
```
rules": [
{
"action": "IGNORE_ANOMALY",
"conditions": [
{
"feature_name": "logVolume",
"threshold_type": "
ACTUAL_OVER_EXPECTED_RATIO",
"value": 0.3,
"operator": LTE
}
]
}
]
```
This rule means that we will ignore anomalies if the actual value is less than or equal too 30% higher than the expected.
For example: "Ignore anomalies for feature logVolume when the actual value is no more than 30% above the expected value."
These first sets of threshold are based on either ration or value margin between the actual and expected value compared to a given value by the user. These …
=> Adding feature direction rules

src/main/java/org/opensearch/timeseries/rest/handler/AbstractTimeSeriesActionHandler.java, src/test/java/org/opensearch/action/admin/indices/mapping/get/IndexAnomalyDetectorActionHandlerTests.java, src/test/java/org/opensearch/action/admin/indices/mapping/get/ValidateAnomalyDetectorActionHandlerTests.java, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java, src/test/java/org/opensearch/ad/transport/ValidateAnomalyDetectorTransportActionTests.java
=> [Backport 2.x] Not blocking detector creation on unknown feature validation error

build.gradle, release-notes/opensearch-anomaly-detection.release-notes-2.18.0.0.md, src/main/java/org/opensearch/forecast/transport/ForecastResultBulkTransportAction.java, src/main/java/org/opensearch/timeseries/rest/handler/IntervalCalculation.java, src/main/java/org/opensearch/timeseries/transport/ResultProcessor.java, src/main/java/org/opensearch/timeseries/transport/handler/ResultIndexingHandler.java, src/test/java/org/opensearch/ad/transport/handler/AnomalyResultHandlerTests.java, src/test/java/org/opensearch/forecast/AbstractForecastSyntheticDataTest.java, src/test/java/org/opensearch/forecast/rest/ForecastRestApiIT.java, src/test/java/org/opensearch/forecast/rest/SecureForecastRestIT.java, src/test/java/org/opensearch/timeseries/AbstractSyntheticDataTest.java, src/test/java/org/opensearch/timeseries/TestHelpers.java, src/test/java/org/opensearch/timeseries/transport/ForecastResultBulkTransportActionTests.java
- **IntervalCalculation**: Prevent an `ArrayIndexOutOfBoundsException` by returning early when there are fewer than two timestamps. Previously, the code assumed at least two timestamps, causing an exception when only one was present.
- **ResultIndexingHandler**: Handle exceptions from asynchronous calls by logging error messages instead of throwing exceptions. Since the caller does not wait for these asynchronous operations, throwing exceptions had no effect and could lead to unhandled exceptions. Logging provides visibility without disrupting the caller's flow.
Testing done:
1. added UT and ITs.
For more information on following …
=> Fix exceptions in IntervalCalculation and ResultIndexingHandler

build.gradle, release-notes/opensearch-anomaly-detection.release-notes-2.18.0.0.md, src/main/java/org/opensearch/forecast/transport/ForecastResultBulkTransportAction.java, src/main/java/org/opensearch/timeseries/rest/handler/IntervalCalculation.java, src/main/java/org/opensearch/timeseries/transport/handler/ResultIndexingHandler.java, src/test/java/org/opensearch/ad/transport/handler/AnomalyResultHandlerTests.java, src/test/java/org/opensearch/forecast/AbstractForecastSyntheticDataTest.java, src/test/java/org/opensearch/forecast/rest/ForecastRestApiIT.java, src/test/java/org/opensearch/forecast/rest/SecureForecastRestIT.java, src/test/java/org/opensearch/timeseries/AbstractSyntheticDataTest.java, src/test/java/org/opensearch/timeseries/TestHelpers.java, src/test/java/org/opensearch/timeseries/transport/ForecastResultBulkTransportActionTests.java
=> [backport to 2.x] Fix exceptions in IntervalCalculation and ResultIndexingHandler 

src/main/java/org/opensearch/timeseries/rest/handler/AbstractTimeSeriesActionHandler.java, src/main/java/org/opensearch/timeseries/util/RestHandlerUtils.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java
update put route to enable flatten result index in put route
=> update put route when flattening result index

.github/workflows/changelog_verifier.yml, CHANGELOG.md, DEVELOPER_GUIDE.md
Add Changelog verifier workflow for creating release notes faster
=> Add Changelog verifier workflow

.github/workflows/test_build_multi_platform.yml, build-tools/coverage.gradle, build.gradle, gradle/wrapper/gradle-wrapper.properties
Upgrade gradle 8.10.2 and JDK 23
Closes https://github.com/opensearch-project/anomaly-detection/issues/1427
- ~~[ ] New functionality includes testing.~~
- ~~[ ] New functionality has been documented.~~
- ~~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~~
- ~~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~~
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/anomaly-detection/blob/main/CONTRIBUTING.md#d …
=> Upgrade gradle 8.10.2 and JDK 23

CHANGELOG.md, release-notes/opensearch-anomaly-detection.release-notes-3.0.0.0-alpha1.md
Adding release notes for 3.0-alpha1
#967 
=> Adding release notes for 3.0-alpha1

CHANGELOG.md, src/main/java/org/opensearch/timeseries/util/CrossClusterConfigUtils.java, src/test/java/org/opensearch/timeseries/util/CrossClusterConfigUtilsTests.java
Added `#local` to local cluster when index originates from local cluster name to distinguish from a remote cluster with the same name. `#` isn't valid to use in a cluster name so this wont clash with existing names
=> Distinguish local cluster when local name is same as remote

CHANGELOG.md, release-notes/opensearch-anomaly-detection.release-notes-3.0.0.0-beta1.md
Adding release notes for 3.0.0.0-beta1
#967 
=> Adding release notes for 3.0.0.0-beta1

scripts/integtest.sh
Add integtest.sh to specifically run integTestRemote task
opensearch-project/opensearch-build#3747
```
2> org.opensearch.client.ResponseException: method [PUT], host [https://localhost:9200], URI [_cluster/settings], status line [HTTP/2.0 401 Unauthorized]
Unauthorized
```
- ~~[ ] New functionality includes testing.~~
- ~~[ ] New functionality has been documented.~~
- ~~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~~
- ~~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~~
For more information on …
=> Add integtest.sh to specifically run integTestRemote task

CHANGELOG.md, release-notes/opensearch-anomaly-detection.release-notes-3.0.0.0.md
- adding release notes for 3.0.0
- Release Notes for 3.0.0 should include all changes from alpha1+beta1+GA in 1 file
=> adding release notes for 3.0.0

build.gradle
AD has its guava dependencies set at compileOnly level which means they are not packaged into the AD assembly and available at runtime. 
AD uses these deps at runtime, however, the way this works is because of the extending relationship between AD and JS plugin where the deps of the extended plugin are available to the extending plugin at runtime.
In https://github.com/opensearch-project/job-scheduler/pull/773, guava was removed from JS which means these deps are no longer available to AD at runtime. I'm creating this PR to change the guava deps from compileOnly to implementation to ensure they are included in the assembly and available at runtime.
For more information on …
=> Switch guava deps from compileOnly to implementation

release-notes/opensearch-anomaly-detection.release-notes-3.1.0.0.md, src/main/java/org/opensearch/timeseries/rest/handler/LatestTimeRetriever.java
When the user’s time field mapping didn’t include `epoch_millis`, the numeric bounds we pass to `RangeQueryBuilder` were parsed with the field’s default format (`yyyy-MM-dd HH:mm:ss`), triggering a `SearchPhaseExecutionException: all shards failed`. This PR Import `CommonName` and call `.format(CommonName.EPOCH_MILLIS_FORMAT)` to explicitly tell OpenSearch that the `from/to` values are epoch-millis.
Testing done:
1. added cypress IT: https://tinyurl.com/5n98z3ue …
=> Fix LatestTimeRetriever range query failing on non-epoch date mappings

release-notes/opensearch-anomaly-detection.release-notes-3.1.0.0.md, src/main/java/org/opensearch/ad/ml/ADColdStart.java, src/main/java/org/opensearch/forecast/ml/ForecastCheckpointDao.java, src/main/java/org/opensearch/timeseries/ml/ModelColdStart.java, src/main/java/org/opensearch/timeseries/task/TaskManager.java, src/main/java/org/opensearch/timeseries/transport/BaseSuggestConfigParamTransportAction.java
- Skip checkpoint writes during historical/run once
- Add retryOnConflict to task updates to dodge version clashes
- Switch window-delay calculation from 20 % padding (gap × 1.2) to a bucket-based approach. Motivation: the multiplicative cushion scaled with absolute lag, so a multi-hour ingest gap could inflate the delay into days, causing cold start failures.  Tying the delay to config intervals (plus one safety bucket) keeps it proportional and restores prompt results.
Testing done:
* added IT: https://tinyurl.com/5n98z3ue
For more information on following Developer Certificate of Origin and signing off your …
=> Refine cold-start, window delay, and task updates

build.gradle
Updates build.gradle to conditionally download certificates from security repo only when security tests are being run
TBD
=> Updates build.gradle to conditionally download security certificates

CHANGELOG.md, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/timeseries/ratelimit/BatchWorker.java, src/main/java/org/opensearch/timeseries/ratelimit/RateLimitedRequestWorker.java, src/main/java/org/opensearch/timeseries/ratelimit/SingleRequestWorker.java, src/test/java/org/opensearch/ad/ratelimit/ResultWriteWorkerTests.java, src/test/java/org/opensearch/ad/task/ADTaskManagerTests.java
1. Fix ConcurrentModificationException in BatchWorker execution
2. Fix NullPointerException in ADTaskManager.triageState()
3. Fix NullPointerException with ConcurrentHashMap null key handling
Added tests for these.
Exceptions I saw while running HCAD on multi node cluster before bug fixes:
```
ERROR][o.o.a.t.h.ADIndexMemoryPressureAwareResultHandler] [integTest-0] Error in bulking results
»  java.util.ConcurrentModificationException: null
»       at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
»       at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1628) ~[?:?]
»       at java.base/java.util.AbstractSet.removeAll(AbstractSet.java:175) ~[?:?]
»       at org.opensearch.timeseries.ratelimit.BatchWorker.lambda$execute$1(BatchWorker.java:133) ~[?:?] …
```
=> Fixing concurrency bug on writer

CHANGELOG.md, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/timeseries/ratelimit/BatchWorker.java, src/main/java/org/opensearch/timeseries/ratelimit/RateLimitedRequestWorker.java, src/main/java/org/opensearch/timeseries/ratelimit/SingleRequestWorker.java, src/test/java/org/opensearch/ad/ratelimit/ResultWriteWorkerTests.java, src/test/java/org/opensearch/ad/task/ADTaskManagerTests.java
=> [backport 3.1] Fixing concurrency bug on writer 

src/test/java/org/opensearch/ad/AnomalyDetectorJobRunnerTests.java
This PR is a simple test refactor to remove calling the constructor of LockService directly. I plan to switch LockService to an interface and instruct plugins to get a handle of the LockService instantiated by JS through dependency injection.
=> [Test Refactor] Remove instantiation of LockService from JS and use Mock instead

CHANGELOG.md, build.gradle
Post https://github.com/opensearch-project/security/pull/5671, we require explicit setting of protected resource types. This PR adds that to the test setup.
=> Fix tests by adding the new node setting for protected types

CHANGELOG.md, build.gradle
Long-running tests such as RealTimeRuleModelPerfIT may exceed the default 1200-second timeout and fail to complete within the integTestRemote run. Exclude these tests to prevent timeouts. They are covered by separate CI jobs that run long-running tests during PR validation.
Resolves #[1568]
=> Exclude long-running tests from integTestRemote
