opensearch-project/anomaly-detection

release-notes/opensearch.anomaly-detection.release-notes-1.0.0.0-beta1.md
Adds release notes for 1.0.0.0-beta1
=> Add release notes for version 1.0.0.0-beta1

release-notes/opensearch-anomaly-detection.release-notes-1.0.0.0-beta1.md
1. Removes unnecessary commits in the list
2. Renames file to be consistent with OpenSearch standards
=> Remove unnecessary commits from release notes & rename

DEVELOPER_GUIDE.md, README.md
Signed-off-by: dblock <dblock@amazon.com>
Updated README, added TOC, extracted developer guide. Replaced all ES by OpenSearch except for some links.
Closes #4.
=> Updated README for OpenSearch, split out developer guide.

src/main/java/com/amazon/opendistroforelasticsearch/ad/constant/CommonErrorMessages.java, src/main/java/com/amazon/opendistroforelasticsearch/ad/model/ADTask.java, src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetector.java, src/main/resources/mappings/anomaly-detection-state.json, src/main/resources/mappings/anomaly-detectors.json
Update data model to support unified flow
=> tune data model for unified flow

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorJobRunner.java, src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/ad/model/ADTask.java, src/main/java/com/amazon/opendistroforelasticsearch/ad/model/ADTaskType.java, src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorJobActionHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java, src/main/java/com/amazon/opendistroforelasticsearch/ad/task/ADTaskManager.java, src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyDetectorJobTransportAction.java, src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/DeleteAnomalyDetectorTransportAction.java, src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/GetAnomalyDetectorTransportAction.java, src/test/java/com/amazon/opendistroforelasticsearch/ad/mock/transport/MockAnomalyDetectorJobTransportActionWithUser.java, src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyDetectorJobTransportActionTests.java
Add realtime task for detector realtime job.
1.Create realtime task when start realtime detection.
2.Set realtime task state as stopped when realtime detection job stopped.
=> add realtime task

src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetectorExecutionInput.java, src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestExecuteAnomalyDetectorAction.java, src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestPreviewAnomalyDetectorAction.java, src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/PreviewAnomalyDetectorTransportAction.java, src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/PreviewAnomalyDetectorTransportActionTests.java
In unified flow, user can preview detector before creating. That mean user can pass detector configuration to preview without detector id.
This PR add new URL path `_opendistro/_anomaly_detection/detectors/_preview`. User can preview existing detector as well.
Examples
```
POST _opendistro/_anomaly_detection/detectors/_preview
{
"period_start": 1612982516000,
"period_end": 1614278539000,
"detector": {
"name": "test-detector",
"description": "test",
"time_field": "timestamp",
"indices": [
"test_data"
],
"detection_interval": {
"period": {
"interval": 1,
"unit": "Minutes"
}
},
"feature_attributes": [
{
"feature_name": "feature1",
"feature_enabled": true,
"aggregation_query": {
"feature1": {
"sum": {
"field": "value"
}
}
}
}
]
}
}
POST …
```
=> support preview with detector directly

build.gradle
Signed-off-by: Alex <pengsun@amazon.com>
Update the AD version from beta1 to rc1.
https://github.com/opensearch-project/anomaly-detection/issues/40
- [Y] Commits are signed per the DCO using --signoff 
=> Update the AD version from beta1 to rc1.

release-notes/opensearch-anomaly-detection.release-notes-1.0.0.0-rc1.md
Signed-off-by: Tyler Ohlsen ohltyler@amazon.com
Add release notes for version `1.0.0.0-rc1`.
=> Add release notes for 1.0.0.0-rc1

.github/workflows/CI.yml, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java
Pull docker image and run integration test in CI.
=> Run integration test against docker image in CI

release-notes/opensearch-anomaly-detection.release-notes-1.0.0.0.md
Add release notes for version 1.0.0.0.
=> Add release notes for 1.0.0.0

.github/workflows/CI.yml, build.gradle, release-notes/opensearch-anomaly-detection.release-notes-1.0.0.0.md
Backporting #110 & #111 to `1.x` branch. 
=> [BACKPORT] [1.x] 1.0.0.0 release changes

release-notes/opensearch-anomaly-detection.release-notes-1.0.0.0.md
Signed-off-by: Yaliang Wu <ylwu@dev-dsk-ylwu-2c-e500d1cf.us-west-2.amazon.com>
Add rc1 release notes to GA release.
=> add rc1 release notes to GA release

release-notes/opensearch-anomaly-detection.release-notes-1.0.0.0.md
Signed-off-by: Yaliang Wu <ylwu@dev-dsk-ylwu-2c-e500d1cf.us-west-2.amazon.com>
Backport #116 to 1.x branch.
=> [Backport] [1.x] add rc1 release notes to GA release

release-notes/opensearch-anomaly-detection.release-notes-1.0.0.0.md
Signed-off-by: Yaliang Wu <ylwu@dev-dsk-ylwu-2c-e500d1cf.us-west-2.amazon.com>
Backport #116 to 1.0 branch
=> [BACKPORT] [1.0] add rc1 release notes to GA release

.github/workflows/CI.yml, build.gradle
Backport #114 to 1.0 branch
#153 
=> [BACKPORT] [1.0] Bump plugin dependencies to 1.0.0.0

src/main/java/org/opensearch/ad/ml/ModelManager.java, src/test/java/org/opensearch/ad/ml/ModelManagerTests.java
This pr uses ercf to get anomaly result.
=> get thresholding result from ercf

src/main/java/org/opensearch/ad/ml/EntityColdStarter.java, src/main/java/org/opensearch/ad/ml/EntityModel.java, src/test/java/org/opensearch/ad/ml/EntityColdStarterTests.java, src/test/java/org/opensearch/ad/ml/EntityModelTests.java
Signed-off-by: lai <laijiang@amazon.com>
This pull request training anomaly detection models with ercf.
=> train ercf model

bwctest.sh
Signed-off-by: Sarat Vemulapalli <vemulapallisarat@gmail.com>
Adding support to run BWC tests for nightly and release builds via test pipeline.
Refer to: https://github.com/opensearch-project/opensearch-build/issues/90
https://github.com/opensearch-project/opensearch-build/issues/296
=> Adding support to run BWC tests for nightly and release builds

src/main/java/org/opensearch/ad/cluster/HashRing.java, src/main/java/org/opensearch/ad/constant/CommonErrorMessages.java, src/main/java/org/opensearch/ad/model/ADTask.java, src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/main/java/org/opensearch/ad/model/AnomalyDetectorType.java, src/main/java/org/opensearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java, src/main/java/org/opensearch/ad/settings/LegacyOpenDistroAnomalyDetectorSettings.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/ad/transport/StatsAnomalyDetectorTransportAction.java, src/test/java/org/opensearch/ad/ADIntegTestCase.java, src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/HistoricalAnalysisIntegTestCase.java, src/test/java/org/opensearch/ad/HistoricalAnalysisRestTestCase.java, src/test/java/org/opensearch/ad/TestHelpers.java, src/test/java/org/opensearch/ad/mock/model/MockSimpleLog.java, src/test/java/org/opensearch/ad/model/AnomalyDetectorTests.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/rest/HistoricalAnalysisRestApiIT.java, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java, src/test/java/org/opensearch/ad/settings/AnomalyDetectorSettingsTests.java, src/test/java/org/opensearch/ad/task/ADTaskManagerTests.java, src/test/java/org/opensearch/ad/transport/ADBatchAnomalyResultTransportActionTests.java, src/test/java/org/opensearch/ad/transport/AnomalyDetectorJobTransportActionTests.java, src/test/java/org/opensearch/ad/transport/SearchAnomalyDetectorActionTests.java, src/test/java/org/opensearch/ad/transport/StatsAnomalyDetectorTransportActionTests.java, src/test/java/org/opensearch/ad/util/ParseUtilsTests.java
1. add deprecated detector type for BWC
2. Add more test cases for historical analysis. 
As the first item is needed for BWC, send out test cases I have now to review first. 
Test coverage is still lower than our bar. Working on adding more test cases for historical analysis, will send out separate PR later.
=> add deprecated detector type for bwc; add more test cases for historical analysis

src/main/java/org/opensearch/ad/cluster/HashRing.java, src/main/java/org/opensearch/ad/constant/CommonErrorMessages.java, src/main/java/org/opensearch/ad/model/ADTask.java, src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/main/java/org/opensearch/ad/model/AnomalyDetectorType.java, src/main/java/org/opensearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java, src/main/java/org/opensearch/ad/settings/LegacyOpenDistroAnomalyDetectorSettings.java, src/main/java/org/opensearch/ad/task/ADTaskManager.java, src/main/java/org/opensearch/ad/transport/StatsAnomalyDetectorTransportAction.java, src/test/java/org/opensearch/ad/ADIntegTestCase.java, src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/HistoricalAnalysisIntegTestCase.java, src/test/java/org/opensearch/ad/HistoricalAnalysisRestTestCase.java, src/test/java/org/opensearch/ad/TestHelpers.java, src/test/java/org/opensearch/ad/mock/model/MockSimpleLog.java, src/test/java/org/opensearch/ad/model/AnomalyDetectorTests.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/rest/HistoricalAnalysisRestApiIT.java, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java, src/test/java/org/opensearch/ad/settings/AnomalyDetectorSettingsTests.java, src/test/java/org/opensearch/ad/task/ADTaskManagerTests.java, src/test/java/org/opensearch/ad/transport/ADBatchAnomalyResultTransportActionTests.java, src/test/java/org/opensearch/ad/transport/AnomalyDetectorJobTransportActionTests.java, src/test/java/org/opensearch/ad/transport/SearchAnomalyDetectorActionTests.java, src/test/java/org/opensearch/ad/transport/StatsAnomalyDetectorTransportActionTests.java, src/test/java/org/opensearch/ad/util/ParseUtilsTests.java
Backport PR #197 to 1.x branch
=> [BACKPORT] [1.x] add deprecated detector type for bwc; add more test cases for historical analysis (#197)

release-notes/opensearch-anomaly-detection.release-notes-1.1.0.0.md
Adds release notes for version 1.1.0.0.
Note that if any smaller last-minute changes are made, we don't need to add them to the release notes, as only larger customer-impacting changes should be included in the notes.
=> Add release notes for version 1.1.0.0

release-notes/opensearch-anomaly-detection.release-notes-1.1.0.0.md
=> [BACKPORT] [1.x] Add release notes for version 1.1.0.0 (#203)

release-notes/opensearch-anomaly-detection.release-notes-1.1.0.0.md
=> [BACKPORT] [1.1] Add release notes for version 1.1.0.0 (#203)

src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/main/java/org/opensearch/ad/model/AnomalyDetectorJob.java, src/test/java/org/opensearch/ad/HistoricalAnalysisRestTestCase.java, src/test/java/org/opensearch/ad/TestHelpers.java, src/test/java/org/opensearch/ad/bwc/ADBackwardsCompatibilityIT.java, src/test/java/org/opensearch/ad/rest/ADRestTestUtils.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/rest/HistoricalAnalysisRestApiIT.java
Add more BWC IT test cases. As BWC test framework doesn't provide way to specify which node to send request to, just test happy workflow here. Will add more test cases for edge cases in future.
**[Note]**: This PR is not to cover all happy/edge cases for AD BWC. That's just what I have written currently. Definitely we will/need to add more test cases to improve coverage. 
=> add BWC test cases; fix flaky test

src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/main/java/org/opensearch/ad/model/AnomalyDetectorJob.java, src/main/java/org/opensearch/ad/settings/AnomalyDetectorSettings.java, src/main/java/org/opensearch/ad/settings/LegacyOpenDistroAnomalyDetectorSettings.java, src/test/java/org/opensearch/ad/HistoricalAnalysisRestTestCase.java, src/test/java/org/opensearch/ad/TestHelpers.java, src/test/java/org/opensearch/ad/bwc/ADBackwardsCompatibilityIT.java, src/test/java/org/opensearch/ad/rest/ADRestTestUtils.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/rest/HistoricalAnalysisRestApiIT.java
=> Backport 1.x

src/main/java/org/opensearch/ad/model/AnomalyDetector.java, src/main/java/org/opensearch/ad/model/AnomalyDetectorJob.java, src/main/java/org/opensearch/ad/settings/AnomalyDetectorSettings.java, src/main/java/org/opensearch/ad/settings/LegacyOpenDistroAnomalyDetectorSettings.java, src/test/java/org/opensearch/ad/HistoricalAnalysisRestTestCase.java, src/test/java/org/opensearch/ad/TestHelpers.java, src/test/java/org/opensearch/ad/bwc/ADBackwardsCompatibilityIT.java, src/test/java/org/opensearch/ad/rest/ADRestTestUtils.java, src/test/java/org/opensearch/ad/rest/AnomalyDetectorRestApiIT.java, src/test/java/org/opensearch/ad/rest/HistoricalAnalysisRestApiIT.java
=> Backport 1.1

src/main/java/org/opensearch/ad/rest/RestSearchAnomalyResultAction.java, src/main/java/org/opensearch/ad/transport/SearchAnomalyResultTransportAction.java, src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/model/AnomalyDetectorTests.java, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java, src/test/java/org/opensearch/ad/transport/SearchAnomalyResultActionTests.java
* support only searching results in custom result index
* add/fix comments
=> [Backport to 1.2] support only searching results in custom result index (#292)

src/main/java/org/opensearch/ad/rest/RestSearchAnomalyResultAction.java, src/main/java/org/opensearch/ad/transport/SearchAnomalyResultTransportAction.java, src/test/java/org/opensearch/ad/AnomalyDetectorRestTestCase.java, src/test/java/org/opensearch/ad/model/AnomalyDetectorTests.java, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java, src/test/java/org/opensearch/ad/transport/SearchAnomalyResultActionTests.java
* support only searching results in custom result index
* add/fix comments
=> [Backport to 1.x] support only searching results in custom result index (#292)

release-notes/opensearch-anomaly-detection.release-notes-1.2.0.0.md
=> Backport main branch release notes commits to 1.2 branch

src/main/java/org/opensearch/ad/transport/ValidateAnomalyDetectorTransportAction.java
=> [Backport to 1.2] added switch case for general settings issues (#305)

src/main/java/org/opensearch/ad/transport/ValidateAnomalyDetectorTransportAction.java
=> [Backport to 1.x] added switch case for general settings issues (#305)

release-notes/opensearch-anomaly-detection.release-notes-1.2.0.0.md
Backporting commit #308 to 1.x
=> [Backporting to 1.x] updated release notes for 1.2 backend (#308)

release-notes/opensearch-anomaly-detection.release-notes-1.2.0.0.md
=> [Backporting to 1.2] updated release notes for 1.2 backend (#308)

release-notes/opensearch-anomaly-detection.release-notes-1.2.0.0.md
=> [Backporting to 1.x] changed release notes dashes to asterisks (#313)

release-notes/opensearch-anomaly-detection.release-notes-1.2.0.0.md
=> [Backporting to 1.2] changed release notes dashes to asterisks (#313)

release-notes/opensearch-anomaly-detection.release-notes-1.2.0.1.md
Add release notes for patch version 1.2.0.1.
=> Add patch version 1.2.0.1 release notes

release-notes/opensearch-anomaly-detection.release-notes-1.2.0.1.md
=> [BACKPORT] [1.x] Add patch version 1.2.0.1 release notes (#327)

release-notes/opensearch-anomaly-detection.release-notes-1.2.0.1.md
=> [BACKPORT] [1.2] Add patch version 1.2.0.1 release notes (#327)

.github/workflows/link-check-workflow.yml, build.gradle
Fix missing dependency: commons-lang3. 
https://github.com/opensearch-project/OpenSearch/issues/1851
=> fix missing dependency:commons-lang3

build.gradle
=> [Backport to 1.2] upgrade gson to 2.8.9 (#354)

release-notes/opensearch-anomaly-detection.release-notes-1.2.4.0.md
=> Adds 1.2.4.0 release notes

build.gradle
Upgrade jackson-databind and guava
=> upgrade jackson-databind and guava

src/main/java/org/opensearch/ad/rest/handler/ModelValidationActionHandler.java
Removed checking if all feature fields exists for interval recommendation. For checking only if the feature query is the cause of the issue I check each feature query at a time to see if they are the root cause of the issue instead of all of them at once.
=> Check one feature query at a time - Validate API

release-notes/opensearch-anomaly-detection.release-notes-1.3.0.0.md
=> Add release notes for 1.3.0.0

build.gradle
change default version to 2.0.0-alpha1-SNAPSHOT
=> change default version to 2.0.0-alpha1-SNAPSHOT

build.gradle
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Remove hardcoded values for the qualifiers
#432
=> Remove hardcoded values for the qualifiers

build.gradle
changed from alpha1 to rc1 and add tar to distribution download link 
=> changed to rc1 and add tar to distribution download link

.github/workflows/CI.yml
OS docker image is available.Re-enabled tests which were earlier removed 
resolves https://github.com/opensearch-project/anomaly-detection/issues/491
=> Re-enable Tests for CI workflows

release-notes/opensearch-anomaly-detection.release-notes-2.0.0.0-rc1.md
Signed-off-by: aksingh-es <snghes@amazon.com>
OS 2.0.0-rc1 supported release notes
Fixed review comments from https://github.com/opensearch-project/anomaly-detection/pull/510 
Modified Infrastructure entries to avoid unncessary entried
=> 2.0.0.0-rc1 release notes

.github/workflows/CI.yml, release-notes/opensearch-anomaly-detection.release-notes-2.0.0.0-rc1.md
Backport release notes and docker tests
=> Backport release notes and docker tests

.github/workflows/CI.yml, build.gradle
Coming from https://github.com/opensearch-project/opensearch-build/issues/1805 post release activity. 
=> Version bump to 1.3.2

release-notes/opensearch-anomaly-detection.release-notes-2.0.0.0.md
Signed-off-by: aksingh-es <snghes@amazon.com>
Release notes for 2.0.0 GA
=> GA release notes

release-notes/opensearch-anomaly-detection.release-notes-1.3.3.0.md
=> Add release notes for 1.3.3

release-notes/opensearch-anomaly-detection.release-notes-1.3.3.0.md, src/test/java/org/opensearch/ad/feature/NoPowermockSearchFeatureDaoTests.java
=> add a recent commit to release notes

release-notes/opensearch-anomaly-detection.release-notes-2.0.1.0.md
=> Add 2.0.1 release notes

build.gradle, scripts/build.sh
Adds the custom plugin to publish zips to maven. Introduces a custom build.sh script.
resolves #525 
=> Adding custom plugin to publish zip to maven

release-notes/opensearch-anomaly-detection.release-notes-2.1.0.0.md
=> Add 2.1.0 release notes

release-notes/opensearch-anomaly-detection.release-notes-2.2.0.0.md
=> 2.2 release notes

build.gradle
=> Bump to version 2.3

release-notes/opensearch-anomaly-detection.release-notes-2.3.0.0.md
=> Add 2.3 release notes

build.gradle, src/test/java/org/opensearch/ad/ODFERestTestCase.java, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java
This PR:
- Removes Common Utils dependency from build.gradle dependencies
- Removes Common Utils dependency from the codebase
https://github.com/opensearch-project/opensearch-sdk-java/issues/117
=> [Feature/extensions] Removed Common Utils dependency from AD plugin

release-notes/opensearch-anomaly-detection.release-notes-1.3.6.0.md
=> 1.3.6 release notes

build.gradle
Signed-off-by: Jackie Han <jkhanjob@gmail.com>
Making main branch build on 3.0 for this campaign - https://github.com/opensearch-project/opensearch-plugins/issues/142
https://github.com/opensearch-project/opensearch-plugins/issues/142
https://github.com/opensearch-project/anomaly-detection/issues/614
=> bump version to 3.0.0

build.gradle
Bump jackson-databind to 2.13.4.2
=> Bump jackson-databind to 2.13.4.2

release-notes/opensearch-anomaly-detection.release-notes-2.4.0.0.md
Signed-off-by: Jackie Han <jkhanjob@gmail.com>
Add 2.4 release notes
https://github.com/opensearch-project/anomaly-detection/issues/689
=> Add 2.4 release notes

src/main/java/org/opensearch/ad/util/RestHandlerUtils.java
_Describe what this change achieves._
=> [Feature/extensions] Added coalesceToEmpty method

release-notes/opensearch-anomaly-detection.release-notes-2.4.1.0.md
=> Add 2.4.1 release notes

release-notes/opensearch-anomaly-detection.release-notes-2.4.1.0.md
I made the change since it is more appropriate for a patch release.
=> move one PR from enhancement to infrastructure

build.gradle
updating bwc to point to 2.5.0 for main
=> update bwc to 2.5

build.gradle
Signed-off-by: Ryan Bogan <rbogan@amazon.com>
Jackson is no longer in core, so restoring changes made for https://github.com/opensearch-project/anomaly-detection/issues/756
=> Add jackson back to build.gradle

release-notes/opensearch-anomaly-detection.release-notes-2.5.0.0.md
=> Adding 2.5 release notes

.github/workflows/CI.yml, build.gradle, src/main/java/org/opensearch/ad/AnomalyDetectorExtension.java
Signed-off-by: Varun Jain <varunudr@amazon.com>
Changing branch of OpenSearch in CI workflow from feature/extensions to main
=> CI_change_opensearch_branch

release-notes/opensearch-anomaly-detection.release-notes-1.3.8.0.md
=> add 1.3.8 release notes

build.gradle
Refactored build.gradle now since we have JS and OpenSearch 3.0 published to central.
=> [Feature/extension] Refactored build.gradle

release-notes/opensearch-anomaly-detection.release-notes-2.6.0.0.md
Add 2.6 release note
https://github.com/opensearch-project/anomaly-detection/issues/812
=> Add 2.6 release note

.github/workflows/CI.yml
As the part of the integration tests, I figured out since we have merged `feature/extensions` to `main` on OpenSearch and also we are publishing SDK to maven. We don't need to publish it to local anymore.
=> [Feature/Extensions] Improved the CI for AD Extension

src/main/java/org/opensearch/ad/feature/SearchFeatureDao.java, src/main/java/org/opensearch/ad/indices/AnomalyDetectionIndices.java, src/main/java/org/opensearch/ad/rest/AbstractAnomalyDetectorAction.java
This is a re-submission of #834 that I accidentally deleted due to branch naming confusion and force pushing.  Commits in this PR were originally made by @qchimera. 
Update using of non-map addSettingsUpdateConsumer method since it's to be removed from the SDK project.
Fixed incorrect doc param definition on the way.
Updating the use of the addSettingsUpdateConsumer method to work without a map, since the method is to be removed from the SDK project.
opensearch-project/opensearch-sdk-java#522
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING …
=> [Feature/extensions] Integrate SettingsUpdateConsumer code to original following SDK updates

src/main/java/org/opensearch/ad/transport/handler/ADSearchHandler.java, src/main/java/org/opensearch/ad/util/ParseUtils.java, src/test/java/org/opensearch/ad/rest/SecureADRestIT.java, src/test/java/org/opensearch/ad/util/ParseUtilsTests.java
=> [Backport 2.x] Giving admin priority over backendrole filtering (#850)

src/main/java/org/opensearch/ad/transport/handler/AnomalyIndexHandler.java, src/main/java/org/opensearch/ad/util/ExceptionUtil.java, src/main/java/org/opensearch/ad/util/ParseUtils.java, src/test/java/org/opensearch/ad/cluster/HashRingTests.java, src/test/java/org/opensearch/ad/ml/EntityColdStarterTests.java, src/test/java/org/opensearch/ad/ratelimit/CheckpointReadWorkerTests.java, src/test/java/org/opensearch/ad/ratelimit/CheckpointWriteWorkerTests.java, src/test/java/org/opensearch/ad/ratelimit/EntityColdStartWorkerTests.java, src/test/java/org/opensearch/ad/ratelimit/ResultWriteWorkerTests.java, src/test/java/org/opensearch/ad/transport/handler/AnomalyResultHandlerTests.java
Update OpenSearchRejectedExecutionException import
https://github.com/opensearch-project/anomaly-detection/issues/853
=> Update OpenSearchRejectedExecutionException import

release-notes/opensearch-anomaly-detection.release-notes-2.7.0.0.md
Add 2.7 release notes
https://github.com/opensearch-project/anomaly-detection/issues/851
=> Add 2.7 release notes

src/main/java/org/opensearch/ad/AnomalyDetectorExtension.java, src/main/java/org/opensearch/ad/model/AnomalyResultBucket.java, src/main/java/org/opensearch/ad/rest/RestSearchTopAnomalyResultAction.java, src/main/java/org/opensearch/ad/transport/SearchTopAnomalyResultTransportAction.java, src/test/java/org/opensearch/ad/transport/SearchTopAnomalyResultTransportActionTests.java
This PR migrates Search Top Anomalies Results to extension for the below requests.
https://github.com/opensearch-project/opensearch-sdk-java/issues/379
=> [Extensions] Migrated Search Top Anomaly Result to extension

src/main/java/org/opensearch/ad/rest/RestSearchTopAnomalyResultAction.java, src/main/java/org/opensearch/ad/transport/SearchTopAnomalyResultTransportAction.java
Since the PR was merged when I was just about to push my changes. This PR addresses the comments added by @vibrantvarun on https://github.com/opensearch-project/anomaly-detection/pull/884
=> [Extensions] Updates client name for Search Top Anomalies Detector

build.gradle, src/main/java/org/opensearch/ad/settings/EnabledSetting.java, src/test/java/org/opensearch/ad/caching/PriorityCacheTests.java, src/test/java/org/opensearch/ad/transport/ADTaskProfileTransportActionTests.java
First PR to add unit tests back for AD Extension.
Part of https://github.com/opensearch-project/opensearch-sdk-java/issues/723
=> [Extensions] Added tests for PriorityCache, ADTaskProfileTransportActionTests and increased code coverage

build.gradle, src/main/java/org/opensearch/ad/cluster/ADDataMigrator.java, src/test/java/org/opensearch/ad/caching/PriorityCacheTests.java, src/test/java/org/opensearch/ad/cluster/ADDataMigratorTests.java, src/test/java/org/opensearch/ad/transport/EntityResultTransportActionTests.java
Added tests for ADDataMigratorTests and added code coverage for `EntityResultAction`, `EntityProfile`, `EntityResultTransportAction` and `ADDataMigrator`.
=> [Extensions] Added tests for ADDataMigratorTests

.github/CODEOWNERS, MAINTAINERS.md
Update outdated MAINTAINERS and OWNERS list
https://github.com/opensearch-project/anomaly-detection/issues/808
=> Update outdated MAINTAINERS and OWNERS list

.github/CODEOWNERS, MAINTAINERS.md
Updated the list to continue the development work on [feature/extensions](https://github.com/opensearch-project/anomaly-detection/tree/feature/extensions) for AD Extension.
=> [Extensions] Updated Maintainers and CODE_OWNERS list

build.gradle
[Release 1.3.10]Update the common util ref
https://github.com/opensearch-project/anomaly-detection/issues/904
Part of: https://github.com/opensearch-project/opensearch-build/issues/3331
=> [Release 1.3.10]Update the common util ref

release-notes/opensearch-anomaly-detection.release-notes-2.8.0.0.md
=> add 2.8 release notes

build.gradle, src/test/java/org/opensearch/ad/ExtensionsRunnerForTest.java, src/test/java/org/opensearch/ad/NodeStateManagerTests.java
Added tests for NodeStateManager
Part of https://github.com/opensearch-project/opensearch-sdk-java/issues/723
=> [Extensions] Added tests for NodeStateManager

build.gradle
=> [2.x] bumping guava version

build.gradle
=> Bumping guava version

src/main/java/org/opensearch/ad/indices/AnomalyDetectionIndices.java
In this PR, we temporarily enforce DOCUMENT replication for AD indices. This change is necessary due to the current limitation of SegRep, which doesn't support Get/MultiGet by ID. This measure will be in place until SegRep adds support for these operations.
This adjustment aligns with the modification made in the referenced PR: opensearch-project/job-scheduler#417
https://github.com/opensearch-project/anomaly-detection/issues/936
=> [backport to 2.x] Enforce DOCUMENT Replication for AD Indices

release-notes/opensearch-anomaly-detection.release-notes-2.10.0.0.md
Add 2.10 release notes
2.10 release
=> Add 2.10 release notes

release-notes/opensearch-anomaly-detection.release-notes-1.3.13.0.md
=> add 1.3.13 release notes

.github/workflows/benchmark.yml, .github/workflows/test_build_multi_platform.yml, .github/workflows/test_bwc.yml, .github/workflows/test_security.yml
Onboarding jenkins prod docker images to github actions
#1073
=> Onboarding jenkins prod docker images to github actions

build.gradle
Updated lucene snapshot url
Closes https://github.com/opensearch-project/anomaly-detection/issues/1126
=> Updated lucene snapshot url

build.gradle, dataGeneration/requirements.txt
Backport 353dcaeb05f8b75fa74d92e2ae8415ab018bc68e from #1102.
=> [Backport 2.x] Fix build, update CVE-affected versions (#1102)

release-notes/opensearch-anomaly-detection.release-notes-2.12.0.0.md
=> add 2.12 release notes

build.gradle
Fixed lucene url
https://github.com/opensearch-project/opensearch-build/issues/3874#issuecomment-1934891715
=> Fixed lucene url

release-notes/opensearch-anomaly-detection.release-notes-2.13.0.0.md
https://github.com/opensearch-project/anomaly-detection/issues/1160
=> Adding 2.13 release notes

.github/workflows/test_build_multi_platform.yml, release-notes/opensearch-anomaly-detection.release-notes-2.14.0.0.md
Adds 2.14.0 release notes
Part of #1175
=> Add release notes for 2.14.0

release-notes/opensearch-anomaly-detection.release-notes-2.15.0.0.md
=> Adding 2.15 release notes

release-notes/opensearch-anomaly-detection.release-notes-2.16.0.0.md
=> add 2.16 release note

.github/workflows/test_build_multi_platform.yml, .github/workflows/test_bwc.yml, .github/workflows/test_security.yml
=> [1.3] Removed support for JDK8

release-notes/opensearch-anomaly-detection.release-notes-1.3.19.0.md
=> [1.3] Added release notes for 1.3.19

release-notes/opensearch-anomaly-detection.release-notes-2.17.0.0.md
=> release notes for 2.17

release-notes/opensearch-anomaly-detection.release-notes-2.17.1.0.md
=> add 2.17.1 release notes

release-notes/opensearch-anomaly-detection.release-notes-2.17.0.0.md, release-notes/opensearch-anomaly-detection.release-notes-2.17.1.0.md
=> fix release notes typo

.github/workflows/draft-release-notes-workflow.yml, build.gradle
=> [Backport 2.x] Updating several dependencies #1337

.github/workflows/benchmark.yml, .github/workflows/link-check-workflow.yml, .github/workflows/long_running.yml, .github/workflows/maven-publish.yml, .github/workflows/test_build_multi_platform.yml, .github/workflows/test_bwc.yml, build.gradle
=> [Backport 2.x] updating several dependencies (#1368)

release-notes/opensearch-anomaly-detection.release-notes-2.19.0.0.md
=> Add release notes for 2.19.0

CHANGELOG.md, build.gradle
Increment version to 3.0.0.0-beta1
related #967 
=> Increment version to 3.0.0.0-beta1

CHANGELOG.md, release-notes/opensearch-anomaly-detection.release-notes-3.1.0.0.md
https://github.com/opensearch-project/anomaly-detection/issues/1469
=> adding release notes for 3.1.0

release-notes/opensearch-anomaly-detection.release-notes-2.19.3.0.md
=> Adding 2.19.3.0 release notes

CHANGELOG.md, src/main/java/org/opensearch/ad/rest/RestAnomalyDetectorSuggestAction.java, src/main/java/org/opensearch/ad/transport/ADSuggestName.java, src/main/java/org/opensearch/ad/transport/SuggestAnomalyDetectorParamAction.java, src/main/java/org/opensearch/ad/transport/SuggestAnomalyDetectorParamTransportAction.java, src/main/java/org/opensearch/forecast/transport/ForecastSuggestName.java, src/main/java/org/opensearch/forecast/transport/SuggestForecasterParamTransportAction.java, src/main/java/org/opensearch/timeseries/TimeSeriesAnalyticsPlugin.java, src/main/java/org/opensearch/timeseries/transport/BaseSuggestConfigParamTransportAction.java, src/test/java/org/opensearch/ad/rest/DataDependentADRestApiIT.java
Adding suggest API for AD, using similar implementation as forecasting has. 
=> adding AD suggest API
